/**
 * Render a token value, preserving alias references as `var(--kp-…)` when
 * `outputReferences` is on. Mirrors the built-in css/variables behavior so
 * our custom formats keep the same alias chain.
 */
const renderRefValue = function (token) {
  const orig = token.original?.$value ?? token.original?.value;
  if (typeof orig === 'string' && /^\{[^}]+\}$/.test(orig)) {
    const path = orig.slice(1, -1).split('.');
    return `var(--kp-${path.join('-')})`;
  }
  return token.$value ?? token.value;
};

/**
 * Custom format for tokens.css (light).
 *
 * Built-in `css/variables` only writes to `:root {}`. We need light values to
 * also bind to `[data-theme="light"]` so a nested wrapper can restore light
 * inside a globally-dark page (used by the Foundations / Dark Theme Audit
 * page that puts side-by-side `[data-theme="light"]` and `[data-theme="dark"]`
 * columns).
 *
 * Selector list: `:root, :root[data-theme="light"], [data-theme="light"]`.
 * The bare `:root` keeps default-to-light behavior; the two `[data-theme=
 * "light"]` selectors handle nested restoration regardless of whether
 * `:root` itself carries the attribute.
 */
const cssVariablesLight = function ({ dictionary, options }) {
  const useRefs = options?.outputReferences;
  const lines = dictionary.allTokens.map((t) => {
    const value = useRefs ? renderRefValue(t) : (t.$value ?? t.value);
    const desc = t.$description ? ` /** ${t.$description} */` : '';
    return `  --kp-${t.path.join('-')}: ${value};${desc}`;
  });
  return [
    '/**',
    ' * Do not edit directly, this file was auto-generated.',
    ' */',
    '',
    ':root,',
    ':root[data-theme="light"],',
    '[data-theme="light"] {',
    ...lines,
    '}',
    '',
  ].join('\n');
};

/**
 * Generic per-theme CSS format — one factory-driven format for every theme
 * under tokens/themes/*.json (dark, high-contrast, …). Replaces the old
 * single-purpose `css/variables-dark`.
 *
 * Built-in `css/variables` writes to `:root {}`. A theme override file needs:
 *   1. A theme-scoped selector (`[data-theme="<name>"]`).
 *   2. A static prelude that isn't a CSS variable — `color-scheme`, plus the
 *      body `background-color` / `color` so the theme paints the page chrome
 *      even before any component mounts.
 *
 * Everything theme-specific (the selector name, the prelude values, and the
 * architecture note in the header comment) arrives through `options`, so the
 * body of this function is identical for every theme. Run each theme with its
 * own `tokens/themes/<name>.json` as the only source so the output contains
 * only that theme's deltas, not the full token set.
 */
const cssVariablesTheme = function ({ dictionary, options }) {
  const useRefs = options?.outputReferences;
  const { themeName, prelude, note = [] } = options;
  const lines = dictionary.allTokens.map(
    (t) => `  --kp-${t.path.join('-')}: ${useRefs ? renderRefValue(t) : (t.$value ?? t.value)};`,
  );
  const header = [
    '/**',
    ' * Do not edit directly — generated by style-dictionary from',
    ' * tokens/themes/' + themeName + '.json. Run `npm run build:tokens` to regenerate.',
    ...note.map((l) => (l === '' ? ' *' : ` * ${l}`)),
    ' */',
    '',
  ];
  return [
    ...header,
    `:root[data-theme="${themeName}"],`,
    `[data-theme="${themeName}"] {`,
    `  color-scheme: ${prelude.colorScheme};`,
    `  background-color: ${prelude.background};`,
    `  color: ${prelude.color};`,
    '',
    ...lines,
    '}',
    '',
  ].join('\n');
};

// Shared hook: registers both custom formats on every Style Dictionary
// instance. The light config and every theme config inherit them.
const hooks = {
  formats: {
    'css/variables-light': cssVariablesLight,
    'css/variables-theme': cssVariablesTheme,
  },
};

module.exports = {
  hooks,
  source: [
    'tokens/primitive/**/*.json',
    'tokens/semantic/**/*.json',
  ],
  platforms: {
    css: {
      transformGroup: 'css',
      prefix: 'kp',
      buildPath: 'packages/ui/styles/',
      files: [
        {
          destination: 'tokens.css',
          format: 'css/variables-light',
          options: {
            outputReferences: true,
          },
        },
      ],
    },
    scss: {
      transformGroup: 'scss',
      prefix: 'kp',
      buildPath: 'packages/ui/styles/',
      files: [
        {
          destination: '_tokens.scss',
          format: 'scss/variables',
          options: {
            outputReferences: true,
          },
        },
      ],
    },
    ts: {
      transformGroup: 'js',
      prefix: 'kp',
      buildPath: 'packages/ui/src/_generated/',
      files: [
        {
          destination: 'tokens.js',
          format: 'javascript/es6',
        },
      ],
    },
  },
};

// ─── Theme configs (N themes) ─────────────────────────────────────────────
//
// Each theme is `tokens/themes/<name>.json` → `packages/ui/styles/<name>.css`
// under `[data-theme="<name>"]`. They can't just be extra platforms on the
// default config: Style Dictionary would try to resolve every primitive /
// semantic token AND emit them into the theme file, but a theme file must
// contain *only* its overrides — so each theme gets its own config with a
// single-file source list. `scripts/build-tokens.js` loops over `themeConfigs`.
//
// To add a theme: drop `tokens/themes/<name>.json`, add an entry to THEMES
// with its prelude (and an optional header note), and rebuild.
const THEMES = [
  {
    name: 'dark',
    prelude: { colorScheme: 'dark', background: '#09090B', color: '#FAFAFA' },
    note: [
      '',
      'Architecture: every semantic token in tokens.css references a',
      'primitive via var(--kp-color-*). Inverting the primitive ramp',
      'here cascades through the entire system. The handful of explicit',
      'semantic overrides (alert/badge subtle backgrounds) are listed at',
      'the bottom of tokens/themes/dark.json — see that file for why.',
    ],
  },
  {
    name: 'high-contrast',
    prelude: { colorScheme: 'light', background: '#FFFFFF', color: '#000000' },
    note: [
      '',
      'High-contrast (first pass): a light-based maximum-contrast theme. The',
      'gray ramp is pushed to a black-on-white ladder so text, borders and',
      'muted text all clear WCAG AAA (>=7:1); accents keep their light-theme',
      '(strongest) stops. A handful of gray-200/300 stops that double as tinted',
      'surfaces are pinned back to light explicitly so their content stays',
      'readable — see tokens/themes/high-contrast.json for the full rationale.',
    ],
  },
];

function makeThemeConfig(theme) {
  return {
    hooks,
    source: [`tokens/themes/${theme.name}.json`],
    platforms: {
      css: {
        transformGroup: 'css',
        prefix: 'kp',
        buildPath: 'packages/ui/styles/',
        files: [
          {
            destination: `${theme.name}.css`,
            format: 'css/variables-theme',
            // Keep the var() chain for semantic overrides that reference a
            // primitive stop. This makes each theme brand-aware: overriding a
            // --kp-color-<ramp>-* at runtime cascades to these tokens, exactly
            // like the light theme. Primitive ramp stops have no references,
            // so they stay literal.
            options: {
              outputReferences: true,
              themeName: theme.name,
              prelude: theme.prelude,
              note: theme.note,
            },
          },
        ],
      },
    },
  };
}

module.exports.themes = THEMES;
module.exports.makeThemeConfig = makeThemeConfig;
module.exports.themeConfigs = THEMES.map(makeThemeConfig);
