/**
 * Render a token value, preserving alias references as `var(--kp-…)` when
 * `outputReferences` is on. Mirrors the built-in css/variables behavior so
 * our custom formats keep the same alias chain.
 */
const renderRefValue = function (token) {
  const orig = token.original?.$value ?? token.original?.value;
  if (typeof orig === 'string' && /^\{[^}]+\}$/.test(orig)) {
    const path = orig.slice(1, -1).split('.');
    return `var(--kp-${path.join('-')})`;
  }
  return token.$value ?? token.value;
};

/**
 * Custom format for tokens.css (light).
 *
 * Built-in `css/variables` only writes to `:root {}`. We need light values to
 * also bind to `[data-theme="light"]` so a nested wrapper can restore light
 * inside a globally-dark page (used by the Foundations / Dark Theme Audit
 * page that puts side-by-side `[data-theme="light"]` and `[data-theme="dark"]`
 * columns).
 *
 * Selector list: `:root, :root[data-theme="light"], [data-theme="light"]`.
 * The bare `:root` keeps default-to-light behavior; the two `[data-theme=
 * "light"]` selectors handle nested restoration regardless of whether
 * `:root` itself carries the attribute.
 */
const cssVariablesLight = function ({ dictionary, options }) {
  const useRefs = options?.outputReferences;
  const lines = dictionary.allTokens.map((t) => {
    const value = useRefs ? renderRefValue(t) : (t.$value ?? t.value);
    const desc = t.$description ? ` /** ${t.$description} */` : '';
    return `  --kp-${t.path.join('-')}: ${value};${desc}`;
  });
  return [
    '/**',
    ' * Do not edit directly, this file was auto-generated.',
    ' */',
    '',
    ':root,',
    ':root[data-theme="light"],',
    '[data-theme="light"] {',
    ...lines,
    '}',
    '',
  ].join('\n');
};

/**
 * Custom format for dark.css.
 *
 * Built-in `css/variables` writes to `:root {}`. Dark theme needs:
 *   1. A different selector (`[data-theme="dark"]`).
 *   2. A static prelude that isn't a CSS variable (color-scheme, body bg/fg).
 *
 * This format prints the prelude, then every token in the dictionary as a
 * CSS custom property. Run with `tokens/themes/dark.json` as the only source
 * so the output contains only the deltas, not the full token set.
 */
const cssVariablesDark = function ({ dictionary }) {
  const lines = dictionary.allTokens.map(
    (t) => `  --kp-${t.path.join('-')}: ${t.$value ?? t.value};`,
  );
  return [
    '/**',
    ' * Do not edit directly — generated by style-dictionary from',
    ' * tokens/themes/dark.json. Run `npm run build:tokens` to regenerate.',
    ' *',
    ' * Architecture: every semantic token in tokens.css references a',
    ' * primitive via var(--kp-color-*). Inverting the primitive ramp',
    ' * here cascades through the entire system. The handful of explicit',
    ' * semantic overrides (alert/badge subtle backgrounds) are listed at',
    ' * the bottom of tokens/themes/dark.json — see that file for why.',
    ' */',
    '',
    ':root[data-theme="dark"],',
    '[data-theme="dark"] {',
    '  color-scheme: dark;',
    '  background-color: #09090B;',
    '  color: #FAFAFA;',
    '',
    ...lines,
    '}',
    '',
  ].join('\n');
};

// Shared hook: registers both custom formats on every Style Dictionary
// instance. Both configs (light + dark) inherit them.
const hooks = {
  formats: {
    'css/variables-light': cssVariablesLight,
    'css/variables-dark': cssVariablesDark,
  },
};

module.exports = {
  hooks,
  source: [
    'tokens/primitive/**/*.json',
    'tokens/semantic/**/*.json',
  ],
  platforms: {
    css: {
      transformGroup: 'css',
      prefix: 'kp',
      buildPath: 'packages/ui/styles/',
      files: [
        {
          destination: 'tokens.css',
          format: 'css/variables-light',
          options: {
            outputReferences: true,
          },
        },
      ],
    },
    scss: {
      transformGroup: 'scss',
      prefix: 'kp',
      buildPath: 'packages/ui/styles/',
      files: [
        {
          destination: '_tokens.scss',
          format: 'scss/variables',
          options: {
            outputReferences: true,
          },
        },
      ],
    },
    ts: {
      transformGroup: 'js',
      prefix: 'kp',
      buildPath: 'packages/ui/src/_generated/',
      files: [
        {
          destination: 'tokens.js',
          format: 'javascript/es6',
        },
      ],
    },
  },
};

// Dark theme config — invoked separately by scripts/build-tokens.js. We can't
// just add another platform to the same config because Style Dictionary would
// try to resolve every primitive/semantic token AND emit them into dark.css;
// the dark file should contain *only* the overrides, so it gets its own
// source list (one file: tokens/themes/dark.json).
module.exports.dark = {
  hooks,
  source: ['tokens/themes/dark.json'],
  platforms: {
    cssDark: {
      transformGroup: 'css',
      prefix: 'kp',
      buildPath: 'packages/ui/styles/',
      files: [
        {
          destination: 'dark.css',
          format: 'css/variables-dark',
        },
      ],
    },
  },
};
