// AUTO-GENERATED by scripts/generate-react-wrappers.js — do not edit.
// Typed React wrappers over the @kanso-protocol/elements <kp-*> custom
// elements: 75 components, 556 inputs, 87 events.
//
// React <=18 passes unknown JSX props to a custom element as string
// attributes and has no on<event> path, so object/array inputs and DOM events
// need a ref + useEffect (see docs/web-components.md). These wrappers bake
// that in: primitive inputs are set as attributes (via JSX), object/array
// inputs as JS properties (through a ref), and each @Output() foo is exposed
// as an onFoo prop wired via add/removeEventListener with event.detail typed.
/* eslint-disable @typescript-eslint/no-explicit-any */
import * as React from 'react';

// Side-effect import: defines every <kp-*> custom element on load. At runtime
// this is the consumer's peer dependency; the in-repo build resolves it via
// the ambient fallback in ./elements-shim.d.ts (the real types ship with the
// installed package).
import '@kanso-protocol/elements';

/** Handler for a Kanso @Output() — receives the DOM CustomEvent whose
 *  detail is the emitted value. */
export type KpEventHandler<T> = (event: CustomEvent<T>) => void;

/** Props common to every Kanso React wrapper. Standard host attributes plus
 *  data-/aria-* pass-through; deliberately no string index signature, so an
 *  unknown prop is a type error. */
export interface KpCommonProps {
  children?: React.ReactNode;
  className?: string;
  id?: string;
  slot?: string;
  style?: React.CSSProperties;
  title?: string;
  role?: React.AriaRole;
  tabIndex?: number;
  hidden?: boolean;
  onClick?: React.MouseEventHandler<HTMLElement>;
  [dataAttr: `data-${string}`]: unknown;
  [ariaAttr: `aria-${string}`]: unknown;
}

/** A generated wrapper: a forwardRef component whose ref is the underlying
 *  custom element (an HTMLElement). */
export type KpComponent<P> = React.ForwardRefExoticComponent<
  React.PropsWithoutRef<P> & React.RefAttributes<HTMLElement>
>;

interface KpWrapperMeta {
  /** React on<Event> prop name → DOM event name (the @Output() property). */
  readonly events: Readonly<Record<string, string>>;
  /** Input names that must be assigned as JS properties (object/array). */
  readonly properties: readonly string[];
}

function assignRef(ref: React.Ref<HTMLElement> | undefined, value: HTMLElement | null): void {
  if (typeof ref === 'function') ref(value);
  else if (ref) (ref as React.MutableRefObject<HTMLElement | null>).current = value;
}

/** Build one typed forwardRef wrapper for a `kp-*` custom element. */
function createKpWrapper<P extends KpCommonProps>(tag: string, meta: KpWrapperMeta): KpComponent<P> {
  const eventEntries = Object.entries(meta.events); // [reactProp, domEvent][]
  const propertyNames = meta.properties;

  const Wrapper = React.forwardRef<HTMLElement, P>(function KpWrapper(props, forwardedRef) {
    const elRef = React.useRef<HTMLElement | null>(null);
    // Latest event handlers, keyed by DOM event, read by the listeners below
    // so we subscribe once and always dispatch to the current handler.
    const handlersRef = React.useRef<Record<string, ((e: Event) => void) | undefined>>({});

    const record = props as Record<string, unknown>;
    const attributes: Record<string, unknown> = {};
    const handlers: Record<string, ((e: Event) => void) | undefined> = {};
    let children: React.ReactNode;

    for (const key in record) {
      if (key === 'children') {
        children = record[key] as React.ReactNode;
        continue;
      }
      const domEvent = meta.events[key];
      if (domEvent) {
        handlers[domEvent] = record[key] as ((e: Event) => void) | undefined;
        continue;
      }
      if (propertyNames.indexOf(key) !== -1) continue; // object/array → set as property below
      attributes[key] = record[key];
    }
    handlersRef.current = handlers;

    // Stable, up-to-date deps for the property effect (constant length).
    const propertyDeps = propertyNames.map((name) => record[name]);

    const setRef = React.useCallback(
      (node: HTMLElement | null) => {
        elRef.current = node;
        assignRef(forwardedRef, node);
      },
      [forwardedRef],
    );

    // Object/array inputs → JS properties (attributes can only carry strings).
    // Only write props that were actually passed, so element defaults survive.
    React.useEffect(() => {
      const el = elRef.current;
      if (!el) return;
      const target = el as unknown as Record<string, unknown>;
      for (const name of propertyNames) {
        if (name in record) target[name] = record[name];
      }
      // eslint-disable-next-line react-hooks/exhaustive-deps
    }, propertyDeps);

    // @Output() events → DOM CustomEvents. Subscribe once on mount; each
    // listener dispatches to the latest handler via handlersRef.
    React.useEffect(() => {
      const el = elRef.current;
      if (!el || eventEntries.length === 0) return;
      const bound = eventEntries.map(([, domEvent]) => {
        const listener = (event: Event) => {
          const handler = handlersRef.current[domEvent];
          if (handler) handler(event);
        };
        el.addEventListener(domEvent, listener);
        return [domEvent, listener] as const;
      });
      return () => {
        for (const [domEvent, listener] of bound) el.removeEventListener(domEvent, listener);
      };
      // eslint-disable-next-line react-hooks/exhaustive-deps
    }, []);

    return React.createElement(tag, { ...attributes, ref: setRef }, children);
  });

  Wrapper.displayName = tag;
  return Wrapper as KpComponent<P>;
}

export interface KpAccordionProps extends KpCommonProps {
  size?: 'sm' | 'md' | 'lg' | (string & {});
  mode?: 'single' | 'multi' | (string & {});
  showOuterBorder?: boolean | "true" | "false";
}

export const KpAccordion: KpComponent<KpAccordionProps> =
  /*#__PURE__*/ createKpWrapper<KpAccordionProps>('kp-accordion', {
    events: {},
    properties: [],
  });

export interface KpAccordionItemProps extends Omit<KpCommonProps, 'title'> {
  size?: 'sm' | 'md' | 'lg' | (string & {});
  title?: string;
  description?: string;
  showDescription?: boolean | "true" | "false";
  showIconLeft?: boolean | "true" | "false";
  disabled?: boolean | "true" | "false";
  expanded?: boolean | "true" | "false";
  lastInGroup?: boolean | "true" | "false";
  onExpandedChange?: KpEventHandler<boolean>;
}

export const KpAccordionItem: KpComponent<KpAccordionItemProps> =
  /*#__PURE__*/ createKpWrapper<KpAccordionItemProps>('kp-accordion-item', {
    events: { onExpandedChange: 'expandedChange' },
    properties: [],
  });

export interface KpAlertProps extends Omit<KpCommonProps, 'title'> {
  size?: 'sm' | 'md' | 'lg' | (string & {});
  appearance?: 'subtle' | 'solid' | 'outline' | 'left-accent' | (string & {});
  color?: 'primary' | 'danger' | 'success' | 'warning' | 'info' | 'neutral' | (string & {});
  title?: string;
  description?: string;
  actionPlacement?: 'inline' | 'stacked' | (string & {});
  closable?: boolean | "true" | "false";
  onClose?: KpEventHandler<MouseEvent>;
}

export const KpAlert: KpComponent<KpAlertProps> =
  /*#__PURE__*/ createKpWrapper<KpAlertProps>('kp-alert', {
    events: { onClose: 'close' },
    properties: [],
  });

export interface KpAppShellProps extends KpCommonProps {
  layout?: 'sidebar-left' | 'sidebar-right' | 'no-sidebar' | 'sidebar-collapsed' | (string & {});
  showHeader?: boolean | "true" | "false";
  showSidebar?: boolean | "true" | "false";
  showFooter?: boolean | "true" | "false";
  showBanner?: boolean | "true" | "false";
}

export const KpAppShell: KpComponent<KpAppShellProps> =
  /*#__PURE__*/ createKpWrapper<KpAppShellProps>('kp-app-shell', {
    events: {},
    properties: [],
  });

export interface KpAvatarProps extends KpCommonProps {
  size?: 'xs' | 'sm' | 'md' | 'lg' | 'xl' | '2xl' | (string & {});
  shape?: 'circle' | 'square' | (string & {});
  appearance?: 'default' | 'primary' | 'success' | 'warning' | 'danger' | 'info' | 'neutral' | (string & {});
  initials?: string;
  src?: string;
  alt?: string;
  showStatus?: boolean | "true" | "false";
  status?: 'online' | 'offline' | 'busy' | 'away' | (string & {});
  showRing?: boolean | "true" | "false";
  ariaLabelOverride?: string;
}

export const KpAvatar: KpComponent<KpAvatarProps> =
  /*#__PURE__*/ createKpWrapper<KpAvatarProps>('kp-avatar', {
    events: {},
    properties: [],
  });

export interface KpAvatarGroupProps extends KpCommonProps {
  size?: string;
  overlap?: 'tight' | 'normal' | 'loose' | (string & {});
  showCount?: boolean | "true" | "false";
}

export const KpAvatarGroup: KpComponent<KpAvatarGroupProps> =
  /*#__PURE__*/ createKpWrapper<KpAvatarGroupProps>('kp-avatar-group', {
    events: {},
    properties: [],
  });

export interface KpBadgeProps extends KpCommonProps {
  size?: 'xs' | 'sm' | 'md' | (string & {});
  appearance?: 'filled' | 'subtle' | 'outline' | 'dot' | (string & {});
  color?: 'primary' | 'danger' | 'success' | 'warning' | 'info' | 'neutral' | (string & {});
  pill?: boolean | "true" | "false";
  count?: boolean | "true" | "false";
  counter?: number | string;
  showLeadingDot?: boolean | "true" | "false";
  closable?: boolean | "true" | "false";
  onClose?: KpEventHandler<MouseEvent>;
}

export const KpBadge: KpComponent<KpBadgeProps> =
  /*#__PURE__*/ createKpWrapper<KpBadgeProps>('kp-badge', {
    events: { onClose: 'close' },
    properties: [],
  });

export interface KpBannerProps extends Omit<KpCommonProps, 'title'> {
  color?: 'primary' | 'success' | 'warning' | 'danger' | 'info' | 'neutral' | (string & {});
  size?: 'sm' | 'md' | (string & {});
  title?: string;
  description?: string;
  showIcon?: boolean | "true" | "false";
  showClose?: boolean | "true" | "false";
  onClose?: KpEventHandler<void>;
}

export const KpBanner: KpComponent<KpBannerProps> =
  /*#__PURE__*/ createKpWrapper<KpBannerProps>('kp-banner', {
    events: { onClose: 'close' },
    properties: [],
  });

export interface KpBreadcrumbItemProps extends KpCommonProps {
  size?: 'sm' | 'md' | (string & {});
  type?: 'link' | 'current' | 'ellipsis' | (string & {});
  label?: string;
  href?: string;
  disabled?: boolean | "true" | "false";
  ariaLabel?: string;
  onItemClick?: KpEventHandler<MouseEvent>;
}

export const KpBreadcrumbItem: KpComponent<KpBreadcrumbItemProps> =
  /*#__PURE__*/ createKpWrapper<KpBreadcrumbItemProps>('kp-breadcrumb-item', {
    events: { onItemClick: 'itemClick' },
    properties: [],
  });

export interface KpBreadcrumbSeparatorProps extends KpCommonProps {
  size?: 'sm' | 'md' | (string & {});
  type?: 'chevron' | 'slash' | 'dot' | (string & {});
}

export const KpBreadcrumbSeparator: KpComponent<KpBreadcrumbSeparatorProps> =
  /*#__PURE__*/ createKpWrapper<KpBreadcrumbSeparatorProps>('kp-breadcrumb-separator', {
    events: {},
    properties: [],
  });

export interface KpBreadcrumbsProps extends KpCommonProps {
  size?: unknown;
  ariaLabel?: string;
}

export const KpBreadcrumbs: KpComponent<KpBreadcrumbsProps> =
  /*#__PURE__*/ createKpWrapper<KpBreadcrumbsProps>('kp-breadcrumbs', {
    events: {},
    properties: ['size'],
  });

export interface KpBreadcrumbsAutoProps extends KpCommonProps {
  size?: unknown;
  separator?: 'chevron' | 'slash' | 'dot' | (string & {});
  ariaLabel?: string;
}

export const KpBreadcrumbsAuto: KpComponent<KpBreadcrumbsAutoProps> =
  /*#__PURE__*/ createKpWrapper<KpBreadcrumbsAutoProps>('kp-breadcrumbs-auto', {
    events: {},
    properties: ['size'],
  });

export interface KpCardProps extends Omit<KpCommonProps, 'title'> {
  size?: 'sm' | 'md' | 'lg' | (string & {});
  appearance?: 'default' | 'muted' | 'subtle' | 'elevated' | 'outline' | (string & {});
  title?: string;
  description?: string;
  showHeader?: boolean | "true" | "false";
  showDescription?: boolean | "true" | "false";
  showHeaderAction?: boolean | "true" | "false";
  showFooter?: boolean | "true" | "false";
  showHeaderDivider?: boolean | "true" | "false";
  showFooterDivider?: boolean | "true" | "false";
  clickable?: boolean | "true" | "false";
  onCardClick?: KpEventHandler<Event>;
}

export const KpCard: KpComponent<KpCardProps> =
  /*#__PURE__*/ createKpWrapper<KpCardProps>('kp-card', {
    events: { onCardClick: 'cardClick' },
    properties: [],
  });

export interface KpCheckboxProps extends KpCommonProps {
  size?: 'sm' | 'md' | 'lg' | (string & {});
  color?: 'primary' | 'danger' | (string & {});
  checked?: boolean | "true" | "false";
  indeterminate?: boolean | "true" | "false";
  disabled?: boolean | "true" | "false";
  required?: boolean | "true" | "false";
  name?: string;
  value?: string;
  forceState?: 'rest' | 'hover' | 'active' | 'focus' | 'disabled' | 'loading' | 'error' | (string & {}) | null;
  hasLabel?: boolean | "true" | "false";
  ariaLabel?: string;
  ariaDescribedby?: string;
  onCheckedChange?: KpEventHandler<boolean>;
}

export const KpCheckbox: KpComponent<KpCheckboxProps> =
  /*#__PURE__*/ createKpWrapper<KpCheckboxProps>('kp-checkbox', {
    events: { onCheckedChange: 'checkedChange' },
    properties: [],
  });

export interface KpComboboxProps extends KpCommonProps {
  size?: 'xs' | 'sm' | 'md' | 'lg' | 'xl' | (string & {});
  placeholder?: string;
  emptyMessage?: string;
  options?: unknown;
  multiple?: boolean | "true" | "false";
  showClear?: boolean | "true" | "false";
  disabled?: boolean | "true" | "false";
  ariaLabel?: string;
  forceState?: 'rest' | 'hover' | 'active' | 'focus' | 'disabled' | 'loading' | 'error' | (string & {}) | null;
  loading?: boolean | "true" | "false";
  serverFilter?: boolean | "true" | "false";
  filterDebounce?: number | string;
  onOpenChange?: KpEventHandler<boolean>;
  onQueryChange?: KpEventHandler<string>;
}

export const KpCombobox: KpComponent<KpComboboxProps> =
  /*#__PURE__*/ createKpWrapper<KpComboboxProps>('kp-combobox', {
    events: { onOpenChange: 'openChange', onQueryChange: 'queryChange' },
    properties: ['options'],
  });

export interface KpCommandPaletteProps extends KpCommonProps {
  size?: 'sm' | 'md' | 'lg' | (string & {});
  open?: boolean | "true" | "false";
  groups?: unknown;
  filter?: string;
  placeholder?: string;
  emptyMessage?: string;
  ariaLabel?: string;
  shortcut?: string;
  onOpenChange?: KpEventHandler<boolean>;
  onFilterChange?: KpEventHandler<string>;
  onItemSelect?: KpEventHandler<unknown>;
}

export const KpCommandPalette: KpComponent<KpCommandPaletteProps> =
  /*#__PURE__*/ createKpWrapper<KpCommandPaletteProps>('kp-command-palette', {
    events: { onOpenChange: 'openChange', onFilterChange: 'filterChange', onItemSelect: 'itemSelect' },
    properties: ['groups'],
  });

export interface KpContainerProps extends KpCommonProps {
  width?: 'narrow' | 'medium' | 'wide' | 'full' | (string & {});
  padding?: 'none' | 'sm' | 'md' | 'lg' | (string & {});
}

export const KpContainer: KpComponent<KpContainerProps> =
  /*#__PURE__*/ createKpWrapper<KpContainerProps>('kp-container', {
    events: {},
    properties: [],
  });

export interface KpDatePickerProps extends KpCommonProps {
  size?: 'xs' | 'sm' | 'md' | 'lg' | 'xl' | (string & {});
  mode?: 'single' | 'range' | (string & {});
  placeholder?: string;
  min?: string;
  max?: string;
  showClear?: boolean | "true" | "false";
  showPresets?: boolean | "true" | "false";
  presets?: unknown;
  firstDayOfWeek?: number | string;
  dateFormatter?: string;
  rangeSeparator?: string;
  disabled?: boolean | "true" | "false";
  forceState?: 'rest' | 'hover' | 'active' | 'focus' | 'disabled' | 'loading' | 'error' | (string & {}) | null;
  onValueChange?: KpEventHandler<unknown>;
  onOpenChange?: KpEventHandler<boolean>;
}

export const KpDatePicker: KpComponent<KpDatePickerProps> =
  /*#__PURE__*/ createKpWrapper<KpDatePickerProps>('kp-date-picker', {
    events: { onValueChange: 'valueChange', onOpenChange: 'openChange' },
    properties: ['presets'],
  });

export interface KpDialogProps extends Omit<KpCommonProps, 'title'> {
  size?: 'xs' | 'sm' | 'md' | 'lg' | 'xl' | (string & {});
  title?: string;
  description?: string;
  showHeroIcon?: boolean | "true" | "false";
  showDescription?: boolean | "true" | "false";
  showFooter?: boolean | "true" | "false";
  showHeaderDivider?: boolean | "true" | "false";
  showFooterDivider?: boolean | "true" | "false";
  footerLayout?: 'start' | 'end' | 'between' | 'stacked' | (string & {});
  ariaLabel?: string;
  closeOnBackdrop?: boolean | "true" | "false";
  closeOnEsc?: boolean | "true" | "false";
  open?: boolean | "true" | "false";
  onOpenChange?: KpEventHandler<boolean>;
  onClosed?: KpEventHandler<void>;
}

export const KpDialog: KpComponent<KpDialogProps> =
  /*#__PURE__*/ createKpWrapper<KpDialogProps>('kp-dialog', {
    events: { onOpenChange: 'openChange', onClosed: 'closed' },
    properties: [],
  });

export interface KpDividerProps extends KpCommonProps {
  orientation?: 'horizontal' | 'vertical' | (string & {});
  label?: string;
  labelPosition?: 'center' | 'start' | 'end' | (string & {});
  hasProjected?: boolean | "true" | "false";
}

export const KpDivider: KpComponent<KpDividerProps> =
  /*#__PURE__*/ createKpWrapper<KpDividerProps>('kp-divider', {
    events: {},
    properties: [],
  });

export interface KpDrawerProps extends Omit<KpCommonProps, 'title'> {
  size?: 'sm' | 'md' | 'lg' | 'xl' | (string & {});
  side?: 'right' | 'left' | 'top' | 'bottom' | (string & {});
  modal?: boolean | "true" | "false";
  variant?: 'flush' | 'floating' | (string & {});
  elevated?: boolean | "true" | "false";
  title?: string;
  description?: string;
  showHeader?: boolean | "true" | "false";
  showDescription?: boolean | "true" | "false";
  showClose?: boolean | "true" | "false";
  showFooter?: boolean | "true" | "false";
  showHeaderDivider?: boolean | "true" | "false";
  showFooterDivider?: boolean | "true" | "false";
  showResizeHandle?: boolean | "true" | "false";
  ariaLabel?: string;
  closeOnBackdrop?: boolean | "true" | "false";
  closeOnEsc?: boolean | "true" | "false";
  open?: boolean | "true" | "false";
  onOpenChange?: KpEventHandler<boolean>;
  onClosed?: KpEventHandler<void>;
}

export const KpDrawer: KpComponent<KpDrawerProps> =
  /*#__PURE__*/ createKpWrapper<KpDrawerProps>('kp-drawer', {
    events: { onOpenChange: 'openChange', onClosed: 'closed' },
    properties: [],
  });

export interface KpDropdownMenuProps extends KpCommonProps {
  hasSearch?: boolean | "true" | "false";
  hasFooter?: boolean | "true" | "false";
  showCancel?: boolean | "true" | "false";
  primaryLabel?: string;
  cancelLabel?: string;
  searchPlaceholder?: string;
  searchValue?: string;
  onSearchChange?: KpEventHandler<string>;
  onPrimary?: KpEventHandler<void>;
  onCancel?: KpEventHandler<void>;
}

export const KpDropdownMenu: KpComponent<KpDropdownMenuProps> =
  /*#__PURE__*/ createKpWrapper<KpDropdownMenuProps>('kp-dropdown-menu', {
    events: { onSearchChange: 'searchChange', onPrimary: 'primary', onCancel: 'cancel' },
    properties: [],
  });

export interface KpEmptyStateProps extends Omit<KpCommonProps, 'title'> {
  size?: 'sm' | 'md' | 'lg' | (string & {});
  title?: string;
  description?: string;
  showIllustration?: boolean | "true" | "false";
  showDescription?: boolean | "true" | "false";
}

export const KpEmptyState: KpComponent<KpEmptyStateProps> =
  /*#__PURE__*/ createKpWrapper<KpEmptyStateProps>('kp-empty-state', {
    events: {},
    properties: [],
  });

export interface KpFileUploadProps extends Omit<KpCommonProps, 'title'> {
  size?: 'sm' | 'md' | 'lg' | (string & {});
  appearance?: 'default' | 'compact' | (string & {});
  multiple?: boolean | "true" | "false";
  accept?: string;
  maxSize?: number | string;
  maxFiles?: number | string;
  disabled?: boolean | "true" | "false";
  required?: boolean | "true" | "false";
  name?: string;
  title?: string;
  hint?: string;
  ariaLabel?: string;
  onFilesAdded?: KpEventHandler<unknown>;
  onFilesRejected?: KpEventHandler<unknown>;
  onFileRemoved?: KpEventHandler<unknown>;
}

export const KpFileUpload: KpComponent<KpFileUploadProps> =
  /*#__PURE__*/ createKpWrapper<KpFileUploadProps>('kp-file-upload', {
    events: { onFilesAdded: 'filesAdded', onFilesRejected: 'filesRejected', onFileRemoved: 'fileRemoved' },
    properties: [],
  });

export interface KpFilterBarProps extends KpCommonProps {
  filters?: unknown;
  showAddFilter?: boolean | "true" | "false";
  showSaveFilter?: boolean | "true" | "false";
  showClearAll?: boolean | "true" | "false";
  onRemoveFilter?: KpEventHandler<string>;
  onAddFilter?: KpEventHandler<void>;
  onSaveFilter?: KpEventHandler<void>;
  onClearAll?: KpEventHandler<void>;
}

export const KpFilterBar: KpComponent<KpFilterBarProps> =
  /*#__PURE__*/ createKpWrapper<KpFilterBarProps>('kp-filter-bar', {
    events: { onRemoveFilter: 'removeFilter', onAddFilter: 'addFilter', onSaveFilter: 'saveFilter', onClearAll: 'clearAll' },
    properties: ['filters'],
  });

export interface KpFormFieldProps extends KpCommonProps {
  label?: string;
  helper?: string;
  required?: 'none' | 'optional' | 'required-asterisk' | (string & {});
  showHelper?: boolean | "true" | "false";
  error?: boolean | "true" | "false";
  disabled?: boolean | "true" | "false";
  errors?: string;
}

export const KpFormField: KpComponent<KpFormFieldProps> =
  /*#__PURE__*/ createKpWrapper<KpFormFieldProps>('kp-form-field', {
    events: {},
    properties: [],
  });

export interface KpFormSectionProps extends Omit<KpCommonProps, 'title'> {
  layout?: 'inline' | 'stacked' | (string & {});
  size?: 'sm' | 'md' | 'lg' | (string & {});
  title?: string;
  description?: string;
  showDescription?: boolean | "true" | "false";
  showDivider?: boolean | "true" | "false";
}

export const KpFormSection: KpComponent<KpFormSectionProps> =
  /*#__PURE__*/ createKpWrapper<KpFormSectionProps>('kp-form-section', {
    events: {},
    properties: [],
  });

export interface KpGridProps extends KpCommonProps {
  columns?: unknown;
  gap?: 'xs' | 'sm' | 'md' | 'lg' | 'xl' | (string & {});
  gapRow?: 'xs' | 'sm' | 'md' | 'lg' | 'xl' | (string & {}) | null;
}

export const KpGrid: KpComponent<KpGridProps> =
  /*#__PURE__*/ createKpWrapper<KpGridProps>('kp-grid', {
    events: {},
    properties: ['columns'],
  });

export interface KpHeaderProps extends KpCommonProps {
  size?: 'sm' | 'md' | 'lg' | (string & {});
  appearance?: 'light' | 'dark' | (string & {});
  showLogo?: boolean | "true" | "false";
  logoText?: string;
  showMainNav?: boolean | "true" | "false";
  navItems?: unknown;
  mobileBreakpoint?: number | string;
  showSearch?: boolean | "true" | "false";
  searchPlaceholder?: string;
  showThemeToggle?: boolean | "true" | "false";
  showNotifications?: boolean | "true" | "false";
  notificationsCount?: number | string;
  showCta?: boolean | "true" | "false";
  ctaLabel?: string;
  showUserMenu?: boolean | "true" | "false";
  userName?: string;
  userRole?: string;
  userInitials?: string;
  showUserStatus?: boolean | "true" | "false";
  onThemeToggle?: KpEventHandler<void>;
  onNotificationsClick?: KpEventHandler<void>;
  onCtaClick?: KpEventHandler<void>;
  onUserMenuClick?: KpEventHandler<void>;
  onMenuClick?: KpEventHandler<void>;
}

export const KpHeader: KpComponent<KpHeaderProps> =
  /*#__PURE__*/ createKpWrapper<KpHeaderProps>('kp-header', {
    events: { onThemeToggle: 'themeToggle', onNotificationsClick: 'notificationsClick', onCtaClick: 'ctaClick', onUserMenuClick: 'userMenuClick', onMenuClick: 'menuClick' },
    properties: ['navItems'],
  });

export interface KpIconProps extends KpCommonProps {

}

export const KpIcon: KpComponent<KpIconProps> =
  /*#__PURE__*/ createKpWrapper<KpIconProps>('kp-icon', {
    events: {},
    properties: [],
  });

export interface KpIconButtonProps extends KpCommonProps {
  size?: 'xs' | 'sm' | 'md' | (string & {});
  ariaLabel?: string;
  disabled?: boolean | "true" | "false";
  onButtonClick?: KpEventHandler<MouseEvent>;
}

export const KpIconButton: KpComponent<KpIconButtonProps> =
  /*#__PURE__*/ createKpWrapper<KpIconButtonProps>('kp-icon-button', {
    events: { onButtonClick: 'buttonClick' },
    properties: [],
  });

export interface KpInputProps extends KpCommonProps {
  size?: 'xs' | 'sm' | 'md' | 'lg' | 'xl' | (string & {});
  type?: string;
  placeholder?: string;
  label?: string;
  ariaLabel?: string;
  floatingLabel?: boolean | "true" | "false";
  showClear?: boolean | "true" | "false";
  disabled?: boolean | "true" | "false";
  forceState?: 'rest' | 'hover' | 'active' | 'focus' | 'disabled' | 'loading' | 'error' | (string & {}) | null;
  value?: string;
}

export const KpInput: KpComponent<KpInputProps> =
  /*#__PURE__*/ createKpWrapper<KpInputProps>('kp-input', {
    events: {},
    properties: [],
  });

export interface KpMarkdownViewerProps extends KpCommonProps {
  size?: 'sm' | 'md' | 'lg' | (string & {});
  content?: string;
  parser?: unknown;
  trusted?: boolean | "true" | "false";
}

export const KpMarkdownViewer: KpComponent<KpMarkdownViewerProps> =
  /*#__PURE__*/ createKpWrapper<KpMarkdownViewerProps>('kp-markdown-viewer', {
    events: {},
    properties: ['parser'],
  });

export interface KpMenuDividerProps extends KpCommonProps {

}

export const KpMenuDivider: KpComponent<KpMenuDividerProps> =
  /*#__PURE__*/ createKpWrapper<KpMenuDividerProps>('kp-menu-divider', {
    events: {},
    properties: [],
  });

export interface KpMenuItemProps extends KpCommonProps {
  size?: 'sm' | 'md' | 'lg' | (string & {});
  label?: string;
  description?: string;
  shortcut?: string;
  hasChevron?: boolean | "true" | "false";
  selected?: boolean | "true" | "false";
  danger?: boolean | "true" | "false";
  disabled?: boolean | "true" | "false";
  forceState?: 'rest' | 'hover' | 'active' | 'focus' | 'disabled' | 'loading' | 'error' | (string & {}) | null;
}

export const KpMenuItem: KpComponent<KpMenuItemProps> =
  /*#__PURE__*/ createKpWrapper<KpMenuItemProps>('kp-menu-item', {
    events: {},
    properties: [],
  });

export interface KpMenuSectionLabelProps extends KpCommonProps {
  label?: string;
}

export const KpMenuSectionLabel: KpComponent<KpMenuSectionLabelProps> =
  /*#__PURE__*/ createKpWrapper<KpMenuSectionLabelProps>('kp-menu-section-label', {
    events: {},
    properties: [],
  });

export interface KpNavItemProps extends KpCommonProps {
  size?: 'sm' | 'md' | 'lg' | (string & {});
  depth?: number | string;
  label?: string;
  active?: boolean | "true" | "false";
  disabled?: boolean | "true" | "false";
  hasChildren?: boolean | "true" | "false";
  expanded?: boolean | "true" | "false";
  showIcon?: boolean | "true" | "false";
  showBadge?: boolean | "true" | "false";
  showActiveIndicator?: boolean | "true" | "false";
  collapsed?: boolean | "true" | "false";
}

export const KpNavItem: KpComponent<KpNavItemProps> =
  /*#__PURE__*/ createKpWrapper<KpNavItemProps>('kp-nav-item', {
    events: {},
    properties: [],
  });

export interface KpNotificationCenterProps extends KpCommonProps {
  state?: 'with-items' | 'empty' | 'loading' | (string & {});
  showFilters?: boolean | "true" | "false";
  activeFilter?: string;
  filters?: unknown;
  showFooter?: boolean | "true" | "false";
  onMarkAllRead?: KpEventHandler<void>;
  onSettingsClick?: KpEventHandler<void>;
  onItemClick?: KpEventHandler<unknown>;
  onFilterChange?: KpEventHandler<string>;
  onViewAll?: KpEventHandler<void>;
  onLoadMore?: KpEventHandler<unknown>;
}

export const KpNotificationCenter: KpComponent<KpNotificationCenterProps> =
  /*#__PURE__*/ createKpWrapper<KpNotificationCenterProps>('kp-notification-center', {
    events: { onMarkAllRead: 'markAllRead', onSettingsClick: 'settingsClick', onItemClick: 'itemClick', onFilterChange: 'filterChange', onViewAll: 'viewAll', onLoadMore: 'loadMore' },
    properties: ['filters'],
  });

export interface KpNotificationItemProps extends Omit<KpCommonProps, 'title'> {
  read?: boolean | "true" | "false";
  title?: string;
  message?: string;
  time?: string;
  icon?: string;
  appearance?: 'primary' | 'success' | 'warning' | 'danger' | 'info' | 'neutral' | (string & {});
  avatarInitials?: string;
  avatarSrc?: string;
}

export const KpNotificationItem: KpComponent<KpNotificationItemProps> =
  /*#__PURE__*/ createKpWrapper<KpNotificationItemProps>('kp-notification-item', {
    events: {},
    properties: [],
  });

export interface KpNumberStepperProps extends KpCommonProps {
  size?: 'xs' | 'sm' | 'md' | 'lg' | 'xl' | (string & {});
  min?: number | string;
  max?: number | string;
  step?: number | string;
  prefix?: string;
  suffix?: string;
  disabled?: boolean | "true" | "false";
  ariaLabel?: string;
  forceState?: 'rest' | 'hover' | 'active' | 'focus' | 'disabled' | 'loading' | 'error' | (string & {}) | null;
}

export const KpNumberStepper: KpComponent<KpNumberStepperProps> =
  /*#__PURE__*/ createKpWrapper<KpNumberStepperProps>('kp-number-stepper', {
    events: {},
    properties: [],
  });

export interface KpPageErrorProps extends Omit<KpCommonProps, 'title'> {
  type?: '404' | '500' | 'offline' | 'access-denied' | (string & {});
  title?: string;
  description?: string;
  icon?: string;
  errorCode?: string;
  showPrimary?: boolean | "true" | "false";
  showSecondary?: boolean | "true" | "false";
}

export const KpPageError: KpComponent<KpPageErrorProps> =
  /*#__PURE__*/ createKpWrapper<KpPageErrorProps>('kp-page-error', {
    events: {},
    properties: [],
  });

export interface KpPageHeaderProps extends Omit<KpCommonProps, 'title'> {
  size?: 'sm' | 'md' | 'lg' | (string & {});
  title?: string;
  description?: string;
  showBreadcrumbs?: boolean | "true" | "false";
  showBackButton?: boolean | "true" | "false";
  showDescription?: boolean | "true" | "false";
  showActions?: boolean | "true" | "false";
  showTabs?: boolean | "true" | "false";
  showBottomDivider?: boolean | "true" | "false";
  align?: 'start' | 'center' | 'end' | (string & {});
  collapsed?: boolean | "true" | "false";
  onBackClick?: KpEventHandler<void>;
}

export const KpPageHeader: KpComponent<KpPageHeaderProps> =
  /*#__PURE__*/ createKpWrapper<KpPageHeaderProps>('kp-page-header', {
    events: { onBackClick: 'backClick' },
    properties: [],
  });

export interface KpPaginationProps extends KpCommonProps {
  size?: unknown;
  navMode?: 'icon' | 'text' | 'icon-text' | (string & {});
  currentPage?: number | string;
  totalPages?: number | string;
  showPrevNext?: boolean | "true" | "false";
  showItemsInfo?: boolean | "true" | "false";
  showItemsPerPage?: boolean | "true" | "false";
  itemsPerPage?: number | string;
  itemsTotal?: number | string;
  itemsPerPageOptions?: unknown;
  itemsPerPageLabel?: string;
  siblingCount?: number | string;
  boundaryCount?: number | string;
  ariaLabel?: string;
  onPageChange?: KpEventHandler<number>;
  onItemsPerPageChange?: KpEventHandler<number>;
}

export const KpPagination: KpComponent<KpPaginationProps> =
  /*#__PURE__*/ createKpWrapper<KpPaginationProps>('kp-pagination', {
    events: { onPageChange: 'pageChange', onItemsPerPageChange: 'itemsPerPageChange' },
    properties: ['size', 'itemsPerPageOptions'],
  });

export interface KpPaginationItemProps extends KpCommonProps {
  size?: 'sm' | 'md' | 'lg' | (string & {});
  type?: 'page' | 'nav' | 'ellipsis' | (string & {});
  page?: number | string;
  selected?: boolean | "true" | "false";
  disabled?: boolean | "true" | "false";
  navMode?: 'icon' | 'text' | 'icon-text' | (string & {});
  navDirection?: 'prev' | 'next' | (string & {});
  navLabel?: string;
  ariaLabel?: string;
  onItemClick?: KpEventHandler<MouseEvent>;
}

export const KpPaginationItem: KpComponent<KpPaginationItemProps> =
  /*#__PURE__*/ createKpWrapper<KpPaginationItemProps>('kp-pagination-item', {
    events: { onItemClick: 'itemClick' },
    properties: [],
  });

export interface KpPopoverProps extends Omit<KpCommonProps, 'title'> {
  size?: 'sm' | 'md' | 'lg' | (string & {});
  arrowPosition?: 'none' | 'top-start' | 'top-center' | 'top-end' | 'right-start' | 'right-center' | 'right-end' | 'bottom-start' | 'bottom-center' | 'bottom-end' | 'left-start' | 'left-center' | 'left-end' | (string & {});
  title?: string;
  description?: string;
  showHeader?: boolean | "true" | "false";
  showHeaderDivider?: boolean | "true" | "false";
  showFooter?: boolean | "true" | "false";
  showFooterDivider?: boolean | "true" | "false";
  closable?: boolean | "true" | "false";
  ariaLabel?: string;
  onClose?: KpEventHandler<MouseEvent>;
}

export const KpPopover: KpComponent<KpPopoverProps> =
  /*#__PURE__*/ createKpWrapper<KpPopoverProps>('kp-popover', {
    events: { onClose: 'close' },
    properties: [],
  });

export interface KpProgressCircularProps extends KpCommonProps {
  size?: 'xs' | 'sm' | 'md' | 'lg' | 'xl' | (string & {});
  color?: 'primary' | 'success' | 'danger' | 'warning' | 'neutral' | (string & {});
  value?: number | string;
  indeterminate?: boolean | "true" | "false";
  showValue?: boolean | "true" | "false";
  ariaLabel?: string;
}

export const KpProgressCircular: KpComponent<KpProgressCircularProps> =
  /*#__PURE__*/ createKpWrapper<KpProgressCircularProps>('kp-progress-circular', {
    events: {},
    properties: [],
  });

export interface KpProgressLinearProps extends KpCommonProps {
  size?: 'xs' | 'sm' | 'md' | 'lg' | (string & {});
  color?: 'primary' | 'success' | 'danger' | 'warning' | 'neutral' | (string & {});
  value?: number | string;
  indeterminate?: boolean | "true" | "false";
  showLabel?: boolean | "true" | "false";
  labelPosition?: 'top' | 'right' | (string & {});
  label?: string;
  ariaLabel?: string;
}

export const KpProgressLinear: KpComponent<KpProgressLinearProps> =
  /*#__PURE__*/ createKpWrapper<KpProgressLinearProps>('kp-progress-linear', {
    events: {},
    properties: [],
  });

export interface KpProgressSegmentedProps extends KpCommonProps {
  size?: 'xs' | 'sm' | 'md' | 'lg' | (string & {});
  color?: 'primary' | 'success' | 'danger' | 'warning' | 'neutral' | (string & {});
  total?: number | string;
  current?: number | string;
  showLabels?: boolean | "true" | "false";
  showStepCounter?: boolean | "true" | "false";
  labels?: unknown;
  stepCounterText?: string;
  ariaLabel?: string;
}

export const KpProgressSegmented: KpComponent<KpProgressSegmentedProps> =
  /*#__PURE__*/ createKpWrapper<KpProgressSegmentedProps>('kp-progress-segmented', {
    events: {},
    properties: ['labels'],
  });

export interface KpRadioProps extends KpCommonProps {
  size?: 'sm' | 'md' | 'lg' | (string & {});
  color?: 'primary' | 'danger' | (string & {});
  value?: string;
  checked?: boolean | "true" | "false";
  disabled?: boolean | "true" | "false";
  required?: boolean | "true" | "false";
  name?: string;
  forceState?: 'rest' | 'hover' | 'active' | 'focus' | 'disabled' | 'loading' | 'error' | (string & {}) | null;
  hasLabel?: boolean | "true" | "false";
  ariaLabel?: string;
  onCheckedChange?: KpEventHandler<boolean>;
}

export const KpRadio: KpComponent<KpRadioProps> =
  /*#__PURE__*/ createKpWrapper<KpRadioProps>('kp-radio', {
    events: { onCheckedChange: 'checkedChange' },
    properties: [],
  });

export interface KpRadioGroupProps extends KpCommonProps {
  value?: string;
  name?: string;
  disabled?: boolean | "true" | "false";
  orientation?: 'vertical' | 'horizontal' | (string & {});
  onValueChange?: KpEventHandler<unknown>;
}

export const KpRadioGroup: KpComponent<KpRadioGroupProps> =
  /*#__PURE__*/ createKpWrapper<KpRadioGroupProps>('kp-radio-group', {
    events: { onValueChange: 'valueChange' },
    properties: [],
  });

export interface KpRichTextEditorProps extends KpCommonProps {
  size?: 'sm' | 'md' | 'lg' | (string & {});
  placeholder?: string;
  disabled?: boolean | "true" | "false";
  error?: boolean | "true" | "false";
  extensions?: 'default' | (string & {});
  onValueChange?: KpEventHandler<string>;
  onImageUpload?: KpEventHandler<unknown>;
}

export const KpRichTextEditor: KpComponent<KpRichTextEditorProps> =
  /*#__PURE__*/ createKpWrapper<KpRichTextEditorProps>('kp-rich-text-editor', {
    events: { onValueChange: 'valueChange', onImageUpload: 'imageUpload' },
    properties: [],
  });

export interface KpRowProps extends KpCommonProps {
  gap?: 'none' | '2xs' | 'xs' | 'sm' | 'md' | 'lg' | 'xl' | '2xl' | (string & {});
  align?: 'start' | 'center' | 'end' | 'stretch' | 'baseline' | (string & {});
  justify?: 'start' | 'center' | 'end' | 'space-between' | 'space-around' | (string & {});
  wrap?: boolean | "true" | "false";
}

export const KpRow: KpComponent<KpRowProps> =
  /*#__PURE__*/ createKpWrapper<KpRowProps>('kp-row', {
    events: {},
    properties: [],
  });

export interface KpSearchBarProps extends KpCommonProps {
  variant?: 'inline' | 'command-palette' | (string & {});
  size?: 'sm' | 'md' | 'lg' | (string & {});
  placeholder?: string;
  value?: string;
  showShortcutHint?: boolean | "true" | "false";
  shortcutHint?: string;
  groups?: unknown;
  onValueChange?: KpEventHandler<string>;
  onSearch?: KpEventHandler<string>;
  onItemClick?: KpEventHandler<unknown>;
}

export const KpSearchBar: KpComponent<KpSearchBarProps> =
  /*#__PURE__*/ createKpWrapper<KpSearchBarProps>('kp-search-bar', {
    events: { onValueChange: 'valueChange', onSearch: 'search', onItemClick: 'itemClick' },
    properties: ['groups'],
  });

export interface KpSegmentedControlProps extends KpCommonProps {
  size?: 'xs' | 'sm' | 'md' | 'lg' | 'xl' | (string & {});
  options?: unknown;
  display?: 'text' | 'icon' | 'icon-text' | (string & {});
  disabled?: boolean | "true" | "false";
  name?: string;
  onValueChange?: KpEventHandler<string>;
}

export const KpSegmentedControl: KpComponent<KpSegmentedControlProps> =
  /*#__PURE__*/ createKpWrapper<KpSegmentedControlProps>('kp-segmented-control', {
    events: { onValueChange: 'valueChange' },
    properties: ['options'],
  });

export interface KpSelectProps extends KpCommonProps {
  size?: 'xs' | 'sm' | 'md' | 'lg' | 'xl' | (string & {});
  placeholder?: string;
  label?: string;
  floatingLabel?: boolean | "true" | "false";
  options?: unknown;
  multiple?: boolean | "true" | "false";
  showClear?: boolean | "true" | "false";
  disabled?: boolean | "true" | "false";
  required?: boolean | "true" | "false";
  name?: string;
  forceState?: 'rest' | 'hover' | 'active' | 'focus' | 'disabled' | 'loading' | 'error' | (string & {}) | null;
  onOpenChange?: KpEventHandler<boolean>;
}

export const KpSelect: KpComponent<KpSelectProps> =
  /*#__PURE__*/ createKpWrapper<KpSelectProps>('kp-select', {
    events: { onOpenChange: 'openChange' },
    properties: ['options'],
  });

export interface KpSettingsPanelProps extends Omit<KpCommonProps, 'title'> {
  size?: 'sm' | 'md' | 'lg' | (string & {});
  title?: string;
  description?: string;
  showHeader?: boolean | "true" | "false";
  showDescription?: boolean | "true" | "false";
  showOuterBorder?: boolean | "true" | "false";
}

export const KpSettingsPanel: KpComponent<KpSettingsPanelProps> =
  /*#__PURE__*/ createKpWrapper<KpSettingsPanelProps>('kp-settings-panel', {
    events: {},
    properties: [],
  });

export interface KpSettingsRowProps extends Omit<KpCommonProps, 'title'> {
  size?: 'sm' | 'md' | 'lg' | (string & {});
  title?: string;
  description?: string;
  showDescription?: boolean | "true" | "false";
  showDivider?: boolean | "true" | "false";
}

export const KpSettingsRow: KpComponent<KpSettingsRowProps> =
  /*#__PURE__*/ createKpWrapper<KpSettingsRowProps>('kp-settings-row', {
    events: {},
    properties: [],
  });

export interface KpSidebarProps extends KpCommonProps {
  widthState?: 'expanded' | 'collapsed' | (string & {});
  appearance?: 'light' | 'dark' | (string & {});
  persistKey?: string;
  showLogo?: boolean | "true" | "false";
  logoText?: string;
  showSearch?: boolean | "true" | "false";
  showSectionLabels?: boolean | "true" | "false";
  showUserFooter?: boolean | "true" | "false";
  sections?: unknown;
  userName?: string;
  userEmail?: string;
  userInitials?: string;
  onToggle?: KpEventHandler<'expanded' | 'collapsed'>;
  onItemClick?: KpEventHandler<unknown>;
  onUserMenuClick?: KpEventHandler<void>;
}

export const KpSidebar: KpComponent<KpSidebarProps> =
  /*#__PURE__*/ createKpWrapper<KpSidebarProps>('kp-sidebar', {
    events: { onToggle: 'toggle', onItemClick: 'itemClick', onUserMenuClick: 'userMenuClick' },
    properties: ['sections'],
  });

export interface KpSkeletonProps extends KpCommonProps {
  shape?: 'line' | 'circle' | 'rectangle' | 'avatar' | 'button' | 'card' | (string & {});
  size?: 'xs' | 'sm' | 'md' | 'lg' | 'xl' | (string & {});
  animated?: boolean | "true" | "false";
  width?: string;
  height?: string;
}

export const KpSkeleton: KpComponent<KpSkeletonProps> =
  /*#__PURE__*/ createKpWrapper<KpSkeletonProps>('kp-skeleton', {
    events: {},
    properties: [],
  });

export interface KpSliderProps extends KpCommonProps {
  size?: 'sm' | 'md' | 'lg' | (string & {});
  mode?: 'single' | 'range' | (string & {});
  min?: number | string;
  max?: number | string;
  step?: number | string;
  showTicks?: boolean | "true" | "false";
  showValueLabel?: boolean | "true" | "false";
  showLabels?: boolean | "true" | "false";
  minLabel?: string;
  maxLabel?: string;
  ariaLabel?: string;
  ariaLabelStart?: string;
  ariaLabelEnd?: string;
  valueFormatter?: number | string;
  onValueChange?: KpEventHandler<unknown>;
}

export const KpSlider: KpComponent<KpSliderProps> =
  /*#__PURE__*/ createKpWrapper<KpSliderProps>('kp-slider', {
    events: { onValueChange: 'valueChange' },
    properties: [],
  });

export interface KpStackProps extends KpCommonProps {
  gap?: 'none' | '2xs' | 'xs' | 'sm' | 'md' | 'lg' | 'xl' | '2xl' | (string & {});
  align?: 'start' | 'center' | 'end' | 'stretch' | (string & {});
}

export const KpStack: KpComponent<KpStackProps> =
  /*#__PURE__*/ createKpWrapper<KpStackProps>('kp-stack', {
    events: {},
    properties: [],
  });

export interface KpStatCardProps extends KpCommonProps {
  size?: 'sm' | 'md' | 'lg' | (string & {});
  label?: string;
  value?: number | string;
  showIcon?: boolean | "true" | "false";
  icon?: string;
  showTrend?: boolean | "true" | "false";
  trendDirection?: 'up' | 'down' | 'neutral' | (string & {});
  trendAppearance?: 'positive' | 'negative' | (string & {});
  trendValue?: string;
  trendDescription?: string;
  showSparkline?: boolean | "true" | "false";
  sparklineData?: unknown;
  sparklineTrend?: string;
}

export const KpStatCard: KpComponent<KpStatCardProps> =
  /*#__PURE__*/ createKpWrapper<KpStatCardProps>('kp-stat-card', {
    events: {},
    properties: ['sparklineData'],
  });

export interface KpTableProps extends KpCommonProps {
  columns?: unknown;
  data?: unknown;
  striped?: boolean | "true" | "false";
  bordered?: boolean | "true" | "false";
  selectable?: boolean | "true" | "false";
  selected?: unknown;
  sort?: string;
  emptyMessage?: string;
  trackBy?: number | string;
  onSelectedChange?: KpEventHandler<unknown>;
  onSortChange?: KpEventHandler<unknown>;
  onRowClick?: KpEventHandler<unknown>;
}

export const KpTable: KpComponent<KpTableProps> =
  /*#__PURE__*/ createKpWrapper<KpTableProps>('kp-table', {
    events: { onSelectedChange: 'selectedChange', onSortChange: 'sortChange', onRowClick: 'rowClick' },
    properties: ['columns', 'data', 'selected'],
  });

export interface KpTableToolbarProps extends KpCommonProps {
  mode?: 'default' | 'bulk-select' | (string & {});
  showSearch?: boolean | "true" | "false";
  searchPlaceholder?: string;
  searchValue?: string;
  showFilter?: boolean | "true" | "false";
  activeFilterCount?: number | string;
  showSort?: boolean | "true" | "false";
  showDensity?: boolean | "true" | "false";
  density?: 'compact' | 'comfortable' | 'spacious' | (string & {});
  showColumnPicker?: boolean | "true" | "false";
  showExport?: boolean | "true" | "false";
  showCreate?: boolean | "true" | "false";
  createLabel?: string;
  selectedCount?: number | string;
  onSearchChange?: KpEventHandler<string>;
  onFilterClick?: KpEventHandler<void>;
  onSortClick?: KpEventHandler<void>;
  onDensityChange?: KpEventHandler<'compact' | 'comfortable' | 'spacious'>;
  onColumnsClick?: KpEventHandler<void>;
  onExportClick?: KpEventHandler<void>;
  onCreateClick?: KpEventHandler<void>;
  onClearSelection?: KpEventHandler<void>;
  onBulkExport?: KpEventHandler<void>;
  onBulkTag?: KpEventHandler<void>;
  onBulkMove?: KpEventHandler<void>;
  onBulkDelete?: KpEventHandler<void>;
}

export const KpTableToolbar: KpComponent<KpTableToolbarProps> =
  /*#__PURE__*/ createKpWrapper<KpTableToolbarProps>('kp-table-toolbar', {
    events: { onSearchChange: 'searchChange', onFilterClick: 'filterClick', onSortClick: 'sortClick', onDensityChange: 'densityChange', onColumnsClick: 'columnsClick', onExportClick: 'exportClick', onCreateClick: 'createClick', onClearSelection: 'clearSelection', onBulkExport: 'bulkExport', onBulkTag: 'bulkTag', onBulkMove: 'bulkMove', onBulkDelete: 'bulkDelete' },
    properties: [],
  });

export interface KpTableVirtualProps extends KpCommonProps {
  columns?: unknown;
  data?: unknown;
  size?: 'sm' | 'md' | 'lg' | (string & {});
  rowHeight?: number | string;
  viewportHeight?: number | string;
  overscan?: number | string;
  striped?: boolean | "true" | "false";
  bordered?: boolean | "true" | "false";
  ariaLabel?: string;
  trackBy?: number | string;
  onRowClick?: KpEventHandler<unknown>;
}

export const KpTableVirtual: KpComponent<KpTableVirtualProps> =
  /*#__PURE__*/ createKpWrapper<KpTableVirtualProps>('kp-table-virtual', {
    events: { onRowClick: 'rowClick' },
    properties: ['columns', 'data'],
  });

export interface KpTabsProps extends KpCommonProps {
  size?: 'sm' | 'md' | 'lg' | (string & {});
  fullWidth?: boolean | "true" | "false";
}

export const KpTabs: KpComponent<KpTabsProps> =
  /*#__PURE__*/ createKpWrapper<KpTabsProps>('kp-tabs', {
    events: {},
    properties: [],
  });

export interface KpTextareaProps extends KpCommonProps {
  size?: 'sm' | 'md' | 'lg' | (string & {});
  placeholder?: string;
  rows?: number | string;
  maxLength?: number | string;
  showCounter?: boolean | "true" | "false";
  resize?: 'both' | 'vertical' | 'horizontal' | 'none' | (string & {});
  filled?: boolean | "true" | "false";
  disabled?: boolean | "true" | "false";
  forceState?: 'rest' | 'hover' | 'active' | 'focus' | 'disabled' | 'loading' | 'error' | (string & {}) | null;
  ariaLabel?: string;
}

export const KpTextarea: KpComponent<KpTextareaProps> =
  /*#__PURE__*/ createKpWrapper<KpTextareaProps>('kp-textarea', {
    events: {},
    properties: [],
  });

export interface KpThemeToggleProps extends KpCommonProps {
  variant?: 'icon' | 'segmented' | 'dropdown' | (string & {});
  size?: 'sm' | 'md' | 'lg' | (string & {});
  currentTheme?: 'light' | 'dark' | 'system' | (string & {});
  showLabel?: boolean | "true" | "false";
  onThemeChange?: KpEventHandler<'light' | 'dark' | 'system'>;
  onDropdownClick?: KpEventHandler<void>;
}

export const KpThemeToggle: KpComponent<KpThemeToggleProps> =
  /*#__PURE__*/ createKpWrapper<KpThemeToggleProps>('kp-theme-toggle', {
    events: { onThemeChange: 'themeChange', onDropdownClick: 'dropdownClick' },
    properties: [],
  });

export interface KpTimePickerProps extends KpCommonProps {
  size?: 'sm' | 'md' | 'lg' | (string & {});
  format?: '12h' | '24h' | 'auto' | (string & {});
  showSeconds?: boolean | "true" | "false";
  minuteStep?: number | string;
  secondStep?: number | string;
  placeholder?: string;
  showClear?: boolean | "true" | "false";
  disabled?: boolean | "true" | "false";
  forceState?: 'rest' | 'hover' | 'active' | 'focus' | 'disabled' | 'loading' | 'error' | (string & {}) | null;
  onValueChange?: KpEventHandler<unknown>;
  onOpenChange?: KpEventHandler<boolean>;
}

export const KpTimePicker: KpComponent<KpTimePickerProps> =
  /*#__PURE__*/ createKpWrapper<KpTimePickerProps>('kp-time-picker', {
    events: { onValueChange: 'valueChange', onOpenChange: 'openChange' },
    properties: [],
  });

export interface KpToastHostProps extends KpCommonProps {
  position?: 'top-right' | 'top-left' | 'bottom-right' | 'bottom-left' | (string & {});
  size?: 'sm' | 'md' | (string & {});
  showIcon?: boolean | "true" | "false";
  max?: number | string;
}

export const KpToastHost: KpComponent<KpToastHostProps> =
  /*#__PURE__*/ createKpWrapper<KpToastHostProps>('kp-toast-host', {
    events: {},
    properties: [],
  });

export interface KpToggleProps extends KpCommonProps {
  size?: 'sm' | 'md' | 'lg' | (string & {});
  color?: 'primary' | 'danger' | (string & {});
  on?: boolean | "true" | "false";
  disabled?: boolean | "true" | "false";
  required?: boolean | "true" | "false";
  name?: string;
  value?: string;
  forceState?: 'rest' | 'hover' | 'active' | 'focus' | 'disabled' | 'loading' | 'error' | (string & {}) | null;
  hasLabel?: boolean | "true" | "false";
  ariaLabel?: string;
  onOnChangeEvent?: KpEventHandler<boolean>;
}

export const KpToggle: KpComponent<KpToggleProps> =
  /*#__PURE__*/ createKpWrapper<KpToggleProps>('kp-toggle', {
    events: { onOnChangeEvent: 'onChangeEvent' },
    properties: [],
  });

export interface KpTreeProps extends KpCommonProps {
  size?: 'sm' | 'md' | (string & {});
  data?: unknown;
  showIcons?: boolean | "true" | "false";
  showCheckboxes?: boolean | "true" | "false";
  expanded?: unknown;
  selected?: string;
  checked?: unknown;
  onExpandedChange?: KpEventHandler<string[]>;
  onSelectedChange?: KpEventHandler<string | null>;
  onCheckedChange?: KpEventHandler<string[]>;
  onNodeClick?: KpEventHandler<unknown>;
  onNodeExpand?: KpEventHandler<unknown>;
}

export const KpTree: KpComponent<KpTreeProps> =
  /*#__PURE__*/ createKpWrapper<KpTreeProps>('kp-tree', {
    events: { onExpandedChange: 'expandedChange', onSelectedChange: 'selectedChange', onCheckedChange: 'checkedChange', onNodeClick: 'nodeClick', onNodeExpand: 'nodeExpand' },
    properties: ['data', 'expanded', 'checked'],
  });

export interface KpUserMenuProps extends KpCommonProps {
  size?: 'sm' | 'md' | (string & {});
  userName?: string;
  userEmail?: string;
  userInitials?: string;
  presence?: 'online' | 'offline' | 'busy' | 'away' | (string & {}) | null;
  showEmail?: boolean | "true" | "false";
  showPlanBadge?: boolean | "true" | "false";
  planName?: string;
  showThemeToggle?: boolean | "true" | "false";
  showHelpLink?: boolean | "true" | "false";
  onSignOut?: KpEventHandler<void>;
}

export const KpUserMenu: KpComponent<KpUserMenuProps> =
  /*#__PURE__*/ createKpWrapper<KpUserMenuProps>('kp-user-menu', {
    events: { onSignOut: 'signOut' },
    properties: [],
  });

export interface KpVariableVirtualListProps extends KpCommonProps {
  items?: unknown;
  itemHeight?: string;
  estimatedItemHeight?: number | string;
  viewportHeight?: number | string;
  overscan?: number | string;
  trackBy?: number | string;
  onRangeChange?: KpEventHandler<unknown>;
}

export const KpVariableVirtualList: KpComponent<KpVariableVirtualListProps> =
  /*#__PURE__*/ createKpWrapper<KpVariableVirtualListProps>('kp-variable-virtual-list', {
    events: { onRangeChange: 'rangeChange' },
    properties: ['items'],
  });

export interface KpVirtualListProps extends KpCommonProps {
  items?: unknown;
  itemHeight?: number | string;
  viewportHeight?: number | string;
  overscan?: number | string;
  trackBy?: number | string;
  onRangeChange?: KpEventHandler<unknown>;
}

export const KpVirtualList: KpComponent<KpVirtualListProps> =
  /*#__PURE__*/ createKpWrapper<KpVirtualListProps>('kp-virtual-list', {
    events: { onRangeChange: 'rangeChange' },
    properties: ['items'],
  });
