// AUTO-GENERATED by scripts/generate-elements-types.js — do not edit.
// Importing '@kanso-protocol/elements' brings these into scope so <kp-*>
// elements type-check in a TSX/React project. Attributes are strings, so
// string-union inputs accept their literal members OR any string.
//
// Event outputs are documented in custom-elements.json (React <=18 wires
// them via addEventListener; React 19 supports on<event> props) and are not
// emitted here to avoid misleading handler typings.

// Minimal, framework-neutral base — avoids depending on React's types so the
// augmentation also works under the classic JSX runtime and other libraries.
interface KpElementBaseAttributes {
  id?: string;
  class?: string;
  className?: string;
  slot?: string;
  part?: string;
  style?: string | Record<string, string | number>;
  title?: string;
  hidden?: boolean;
  tabIndex?: number;
  role?: string;
  children?: unknown;
  key?: string | number;
  ref?: unknown;
  [dataAttr: `data-${string}`]: unknown;
  [ariaAttr: `aria-${string}`]: unknown;
}

declare global {
  interface KpAccordionComponentJsx extends KpElementBaseAttributes {
    size?: 'sm' | 'md' | 'lg' | (string & {});
    mode?: 'single' | 'multi' | (string & {});
    showOuterBorder?: boolean | "true" | "false";
  }
  interface KpAccordionItemComponentJsx extends KpElementBaseAttributes {
    size?: 'sm' | 'md' | 'lg' | (string & {});
    title?: string;
    description?: string;
    showDescription?: boolean | "true" | "false";
    showIconLeft?: boolean | "true" | "false";
    disabled?: boolean | "true" | "false";
    expanded?: boolean | "true" | "false";
    lastInGroup?: boolean | "true" | "false";
  }
  interface KpAlertComponentJsx extends KpElementBaseAttributes {
    size?: 'sm' | 'md' | 'lg' | (string & {});
    appearance?: 'subtle' | 'solid' | 'outline' | 'left-accent' | (string & {});
    color?: 'primary' | 'danger' | 'success' | 'warning' | 'info' | 'neutral' | (string & {});
    title?: string;
    description?: string;
    actionPlacement?: 'inline' | 'stacked' | (string & {});
    closable?: boolean | "true" | "false";
  }
  interface KpAppShellComponentJsx extends KpElementBaseAttributes {
    layout?: 'sidebar-left' | 'sidebar-right' | 'no-sidebar' | 'sidebar-collapsed' | (string & {});
    showHeader?: boolean | "true" | "false";
    showSidebar?: boolean | "true" | "false";
    showFooter?: boolean | "true" | "false";
    showBanner?: boolean | "true" | "false";
  }
  interface KpAvatarComponentJsx extends KpElementBaseAttributes {
    size?: 'xs' | 'sm' | 'md' | 'lg' | 'xl' | '2xl' | (string & {});
    shape?: 'circle' | 'square' | (string & {});
    appearance?: 'default' | 'primary' | 'success' | 'warning' | 'danger' | 'info' | 'neutral' | (string & {});
    initials?: string;
    src?: string;
    alt?: string;
    showStatus?: boolean | "true" | "false";
    status?: 'online' | 'offline' | 'busy' | 'away' | (string & {});
    showRing?: boolean | "true" | "false";
    ariaLabelOverride?: string;
  }
  interface KpAvatarGroupComponentJsx extends KpElementBaseAttributes {
    size?: string;
    overlap?: 'tight' | 'normal' | 'loose' | (string & {});
    showCount?: boolean | "true" | "false";
  }
  interface KpBadgeComponentJsx extends KpElementBaseAttributes {
    size?: 'xs' | 'sm' | 'md' | (string & {});
    appearance?: 'filled' | 'subtle' | 'outline' | 'dot' | (string & {});
    color?: 'primary' | 'danger' | 'success' | 'warning' | 'info' | 'neutral' | (string & {});
    pill?: boolean | "true" | "false";
    count?: boolean | "true" | "false";
    counter?: number | string;
    showLeadingDot?: boolean | "true" | "false";
    closable?: boolean | "true" | "false";
  }
  interface KpBannerComponentJsx extends KpElementBaseAttributes {
    color?: 'primary' | 'success' | 'warning' | 'danger' | 'info' | 'neutral' | (string & {});
    size?: 'sm' | 'md' | (string & {});
    title?: string;
    description?: string;
    showIcon?: boolean | "true" | "false";
    showClose?: boolean | "true" | "false";
  }
  interface KpBreadcrumbItemComponentJsx extends KpElementBaseAttributes {
    size?: 'sm' | 'md' | (string & {});
    type?: 'link' | 'current' | 'ellipsis' | (string & {});
    label?: string;
    href?: string;
    disabled?: boolean | "true" | "false";
    ariaLabel?: string;
  }
  interface KpBreadcrumbSeparatorComponentJsx extends KpElementBaseAttributes {
    size?: 'sm' | 'md' | (string & {});
    type?: 'chevron' | 'slash' | 'dot' | (string & {});
  }
  interface KpBreadcrumbsComponentJsx extends KpElementBaseAttributes {
    size?: any;
    ariaLabel?: string;
  }
  interface KpBreadcrumbsAutoComponentJsx extends KpElementBaseAttributes {
    size?: any;
    separator?: 'chevron' | 'slash' | 'dot' | (string & {});
    ariaLabel?: string;
  }
  interface KpCardComponentJsx extends KpElementBaseAttributes {
    size?: 'sm' | 'md' | 'lg' | (string & {});
    appearance?: 'default' | 'muted' | 'subtle' | 'elevated' | 'outline' | (string & {});
    title?: string;
    description?: string;
    showHeader?: boolean | "true" | "false";
    showDescription?: boolean | "true" | "false";
    showHeaderAction?: boolean | "true" | "false";
    showFooter?: boolean | "true" | "false";
    showHeaderDivider?: boolean | "true" | "false";
    showFooterDivider?: boolean | "true" | "false";
    clickable?: boolean | "true" | "false";
  }
  interface KpCheckboxComponentJsx extends KpElementBaseAttributes {
    size?: 'sm' | 'md' | 'lg' | (string & {});
    color?: 'primary' | 'danger' | (string & {});
    checked?: boolean | "true" | "false";
    indeterminate?: boolean | "true" | "false";
    disabled?: boolean | "true" | "false";
    required?: boolean | "true" | "false";
    name?: string;
    value?: string;
    forceState?: 'rest' | 'hover' | 'active' | 'focus' | 'disabled' | 'loading' | 'error' | (string & {}) | null;
    hasLabel?: boolean | "true" | "false";
    ariaLabel?: string;
    ariaDescribedby?: string;
  }
  interface KpComboboxComponentJsx extends KpElementBaseAttributes {
    size?: 'xs' | 'sm' | 'md' | 'lg' | 'xl' | (string & {});
    placeholder?: string;
    emptyMessage?: string;
    options?: any;
    multiple?: boolean | "true" | "false";
    showClear?: boolean | "true" | "false";
    disabled?: boolean | "true" | "false";
    ariaLabel?: string;
    forceState?: 'rest' | 'hover' | 'active' | 'focus' | 'disabled' | 'loading' | 'error' | (string & {}) | null;
    loading?: boolean | "true" | "false";
    serverFilter?: boolean | "true" | "false";
    filterDebounce?: number | string;
  }
  interface KpCommandPaletteComponentJsx extends KpElementBaseAttributes {
    size?: 'sm' | 'md' | 'lg' | (string & {});
    open?: boolean | "true" | "false";
    groups?: any;
    filter?: string;
    placeholder?: string;
    emptyMessage?: string;
    ariaLabel?: string;
    shortcut?: string;
  }
  interface KpContainerComponentJsx extends KpElementBaseAttributes {
    width?: 'narrow' | 'medium' | 'wide' | 'full' | (string & {});
    padding?: 'none' | 'sm' | 'md' | 'lg' | (string & {});
  }
  interface KpDatePickerComponentJsx extends KpElementBaseAttributes {
    size?: 'xs' | 'sm' | 'md' | 'lg' | 'xl' | (string & {});
    mode?: 'single' | 'range' | (string & {});
    placeholder?: string;
    min?: string;
    max?: string;
    showClear?: boolean | "true" | "false";
    showPresets?: boolean | "true" | "false";
    presets?: any;
    firstDayOfWeek?: number | string;
    dateFormatter?: string;
    rangeSeparator?: string;
    disabled?: boolean | "true" | "false";
    forceState?: 'rest' | 'hover' | 'active' | 'focus' | 'disabled' | 'loading' | 'error' | (string & {}) | null;
  }
  interface KpDialogComponentJsx extends KpElementBaseAttributes {
    size?: 'xs' | 'sm' | 'md' | 'lg' | 'xl' | (string & {});
    title?: string;
    description?: string;
    showHeroIcon?: boolean | "true" | "false";
    showDescription?: boolean | "true" | "false";
    showFooter?: boolean | "true" | "false";
    showHeaderDivider?: boolean | "true" | "false";
    showFooterDivider?: boolean | "true" | "false";
    footerLayout?: 'start' | 'end' | 'between' | 'stacked' | (string & {});
    ariaLabel?: string;
    closeOnBackdrop?: boolean | "true" | "false";
    closeOnEsc?: boolean | "true" | "false";
    open?: boolean | "true" | "false";
  }
  interface KpDividerComponentJsx extends KpElementBaseAttributes {
    orientation?: 'horizontal' | 'vertical' | (string & {});
    label?: string;
    labelPosition?: 'center' | 'start' | 'end' | (string & {});
    hasProjected?: boolean | "true" | "false";
  }
  interface KpDrawerComponentJsx extends KpElementBaseAttributes {
    size?: 'sm' | 'md' | 'lg' | 'xl' | (string & {});
    side?: 'right' | 'left' | 'top' | 'bottom' | (string & {});
    modal?: boolean | "true" | "false";
    variant?: 'flush' | 'floating' | (string & {});
    elevated?: boolean | "true" | "false";
    title?: string;
    description?: string;
    showHeader?: boolean | "true" | "false";
    showDescription?: boolean | "true" | "false";
    showClose?: boolean | "true" | "false";
    showFooter?: boolean | "true" | "false";
    showHeaderDivider?: boolean | "true" | "false";
    showFooterDivider?: boolean | "true" | "false";
    showResizeHandle?: boolean | "true" | "false";
    ariaLabel?: string;
    closeOnBackdrop?: boolean | "true" | "false";
    closeOnEsc?: boolean | "true" | "false";
    open?: boolean | "true" | "false";
  }
  interface KpDropdownMenuComponentJsx extends KpElementBaseAttributes {
    hasSearch?: boolean | "true" | "false";
    hasFooter?: boolean | "true" | "false";
    showCancel?: boolean | "true" | "false";
    primaryLabel?: string;
    cancelLabel?: string;
    searchPlaceholder?: string;
    searchValue?: string;
  }
  interface KpEmptyStateComponentJsx extends KpElementBaseAttributes {
    size?: 'sm' | 'md' | 'lg' | (string & {});
    title?: string;
    description?: string;
    showIllustration?: boolean | "true" | "false";
    showDescription?: boolean | "true" | "false";
  }
  interface KpFileUploadComponentJsx extends KpElementBaseAttributes {
    size?: 'sm' | 'md' | 'lg' | (string & {});
    appearance?: 'default' | 'compact' | (string & {});
    multiple?: boolean | "true" | "false";
    accept?: string;
    maxSize?: number | string;
    maxFiles?: number | string;
    disabled?: boolean | "true" | "false";
    required?: boolean | "true" | "false";
    name?: string;
    title?: string;
    hint?: string;
    ariaLabel?: string;
  }
  interface KpFilterBarComponentJsx extends KpElementBaseAttributes {
    filters?: any;
    showAddFilter?: boolean | "true" | "false";
    showSaveFilter?: boolean | "true" | "false";
    showClearAll?: boolean | "true" | "false";
  }
  interface KpFormFieldComponentJsx extends KpElementBaseAttributes {
    label?: string;
    helper?: string;
    required?: 'none' | 'optional' | 'required-asterisk' | (string & {});
    showHelper?: boolean | "true" | "false";
    error?: boolean | "true" | "false";
    disabled?: boolean | "true" | "false";
    errors?: string;
  }
  interface KpFormSectionComponentJsx extends KpElementBaseAttributes {
    layout?: 'inline' | 'stacked' | (string & {});
    size?: 'sm' | 'md' | 'lg' | (string & {});
    title?: string;
    description?: string;
    showDescription?: boolean | "true" | "false";
    showDivider?: boolean | "true" | "false";
  }
  interface KpGridComponentJsx extends KpElementBaseAttributes {
    columns?: any;
    gap?: 'xs' | 'sm' | 'md' | 'lg' | 'xl' | (string & {});
    gapRow?: 'xs' | 'sm' | 'md' | 'lg' | 'xl' | (string & {}) | null;
  }
  interface KpHeaderComponentJsx extends KpElementBaseAttributes {
    size?: 'sm' | 'md' | 'lg' | (string & {});
    appearance?: 'light' | 'dark' | (string & {});
    showLogo?: boolean | "true" | "false";
    logoText?: string;
    showMainNav?: boolean | "true" | "false";
    navItems?: any;
    mobileBreakpoint?: number | string;
    showSearch?: boolean | "true" | "false";
    searchPlaceholder?: string;
    showThemeToggle?: boolean | "true" | "false";
    showNotifications?: boolean | "true" | "false";
    notificationsCount?: number | string;
    showCta?: boolean | "true" | "false";
    ctaLabel?: string;
    showUserMenu?: boolean | "true" | "false";
    userName?: string;
    userRole?: string;
    userInitials?: string;
    showUserStatus?: boolean | "true" | "false";
  }
  interface KpIconComponentJsx extends KpElementBaseAttributes {

  }
  interface KpIconButtonComponentJsx extends KpElementBaseAttributes {
    size?: 'xs' | 'sm' | 'md' | (string & {});
    ariaLabel?: string;
    disabled?: boolean | "true" | "false";
  }
  interface KpInputComponentJsx extends KpElementBaseAttributes {
    size?: 'xs' | 'sm' | 'md' | 'lg' | 'xl' | (string & {});
    type?: string;
    placeholder?: string;
    label?: string;
    ariaLabel?: string;
    floatingLabel?: boolean | "true" | "false";
    showClear?: boolean | "true" | "false";
    disabled?: boolean | "true" | "false";
    forceState?: 'rest' | 'hover' | 'active' | 'focus' | 'disabled' | 'loading' | 'error' | (string & {}) | null;
    value?: string;
  }
  interface KpMarkdownViewerComponentJsx extends KpElementBaseAttributes {
    size?: 'sm' | 'md' | 'lg' | (string & {});
    content?: string;
    parser?: any;
    trusted?: boolean | "true" | "false";
  }
  interface KpMenuDividerComponentJsx extends KpElementBaseAttributes {

  }
  interface KpMenuItemComponentJsx extends KpElementBaseAttributes {
    size?: 'sm' | 'md' | 'lg' | (string & {});
    label?: string;
    description?: string;
    shortcut?: string;
    hasChevron?: boolean | "true" | "false";
    selected?: boolean | "true" | "false";
    danger?: boolean | "true" | "false";
    disabled?: boolean | "true" | "false";
    forceState?: 'rest' | 'hover' | 'active' | 'focus' | 'disabled' | 'loading' | 'error' | (string & {}) | null;
  }
  interface KpMenuSectionLabelComponentJsx extends KpElementBaseAttributes {
    label?: string;
  }
  interface KpNavItemComponentJsx extends KpElementBaseAttributes {
    size?: 'sm' | 'md' | 'lg' | (string & {});
    depth?: number | string;
    label?: string;
    active?: boolean | "true" | "false";
    disabled?: boolean | "true" | "false";
    hasChildren?: boolean | "true" | "false";
    expanded?: boolean | "true" | "false";
    showIcon?: boolean | "true" | "false";
    showBadge?: boolean | "true" | "false";
    showActiveIndicator?: boolean | "true" | "false";
    collapsed?: boolean | "true" | "false";
  }
  interface KpNotificationCenterComponentJsx extends KpElementBaseAttributes {
    state?: 'with-items' | 'empty' | 'loading' | (string & {});
    notifications?: any;
    pageSize?: number | string;
    showFilters?: boolean | "true" | "false";
    activeFilter?: string;
    filters?: any;
    showFooter?: boolean | "true" | "false";
  }
  interface KpNotificationItemComponentJsx extends KpElementBaseAttributes {
    read?: boolean | "true" | "false";
    title?: string;
    message?: string;
    time?: string;
    icon?: string;
    appearance?: 'primary' | 'success' | 'warning' | 'danger' | 'info' | 'neutral' | (string & {});
    avatarInitials?: string;
    avatarSrc?: string;
  }
  interface KpNumberStepperComponentJsx extends KpElementBaseAttributes {
    size?: 'xs' | 'sm' | 'md' | 'lg' | 'xl' | (string & {});
    min?: number | string;
    max?: number | string;
    step?: number | string;
    prefix?: string;
    suffix?: string;
    disabled?: boolean | "true" | "false";
    ariaLabel?: string;
    forceState?: 'rest' | 'hover' | 'active' | 'focus' | 'disabled' | 'loading' | 'error' | (string & {}) | null;
  }
  interface KpPageErrorComponentJsx extends KpElementBaseAttributes {
    type?: '404' | '500' | 'offline' | 'access-denied' | (string & {});
    title?: string;
    description?: string;
    icon?: string;
    errorCode?: string;
    showPrimary?: boolean | "true" | "false";
    showSecondary?: boolean | "true" | "false";
  }
  interface KpPageHeaderComponentJsx extends KpElementBaseAttributes {
    size?: 'sm' | 'md' | 'lg' | (string & {});
    title?: string;
    description?: string;
    showBreadcrumbs?: boolean | "true" | "false";
    showBackButton?: boolean | "true" | "false";
    showDescription?: boolean | "true" | "false";
    showActions?: boolean | "true" | "false";
    showTabs?: boolean | "true" | "false";
    showBottomDivider?: boolean | "true" | "false";
    align?: 'start' | 'center' | 'end' | (string & {});
    collapsed?: boolean | "true" | "false";
  }
  interface KpPaginationComponentJsx extends KpElementBaseAttributes {
    size?: any;
    navMode?: 'icon' | 'text' | 'icon-text' | (string & {});
    currentPage?: number | string;
    totalPages?: number | string;
    showPrevNext?: boolean | "true" | "false";
    showItemsInfo?: boolean | "true" | "false";
    showItemsPerPage?: boolean | "true" | "false";
    itemsPerPage?: number | string;
    itemsTotal?: number | string;
    itemsPerPageOptions?: any;
    itemsPerPageLabel?: string;
    siblingCount?: number | string;
    boundaryCount?: number | string;
    ariaLabel?: string;
  }
  interface KpPaginationItemComponentJsx extends KpElementBaseAttributes {
    size?: 'sm' | 'md' | 'lg' | (string & {});
    type?: 'page' | 'nav' | 'ellipsis' | (string & {});
    page?: number | string;
    selected?: boolean | "true" | "false";
    disabled?: boolean | "true" | "false";
    navMode?: 'icon' | 'text' | 'icon-text' | (string & {});
    navDirection?: 'prev' | 'next' | (string & {});
    navLabel?: string;
    ariaLabel?: string;
  }
  interface KpPopoverComponentJsx extends KpElementBaseAttributes {
    size?: 'sm' | 'md' | 'lg' | (string & {});
    arrowPosition?: 'none' | 'top-start' | 'top-center' | 'top-end' | 'right-start' | 'right-center' | 'right-end' | 'bottom-start' | 'bottom-center' | 'bottom-end' | 'left-start' | 'left-center' | 'left-end' | (string & {});
    title?: string;
    description?: string;
    showHeader?: boolean | "true" | "false";
    showHeaderDivider?: boolean | "true" | "false";
    showFooter?: boolean | "true" | "false";
    showFooterDivider?: boolean | "true" | "false";
    closable?: boolean | "true" | "false";
    ariaLabel?: string;
  }
  interface KpProgressCircularComponentJsx extends KpElementBaseAttributes {
    size?: 'xs' | 'sm' | 'md' | 'lg' | 'xl' | (string & {});
    color?: 'primary' | 'success' | 'danger' | 'warning' | 'neutral' | (string & {});
    value?: number | string;
    indeterminate?: boolean | "true" | "false";
    showValue?: boolean | "true" | "false";
    ariaLabel?: string;
  }
  interface KpProgressLinearComponentJsx extends KpElementBaseAttributes {
    size?: 'xs' | 'sm' | 'md' | 'lg' | (string & {});
    color?: 'primary' | 'success' | 'danger' | 'warning' | 'neutral' | (string & {});
    value?: number | string;
    indeterminate?: boolean | "true" | "false";
    showLabel?: boolean | "true" | "false";
    labelPosition?: 'top' | 'right' | (string & {});
    label?: string;
    ariaLabel?: string;
  }
  interface KpProgressSegmentedComponentJsx extends KpElementBaseAttributes {
    size?: 'xs' | 'sm' | 'md' | 'lg' | (string & {});
    color?: 'primary' | 'success' | 'danger' | 'warning' | 'neutral' | (string & {});
    total?: number | string;
    current?: number | string;
    showLabels?: boolean | "true" | "false";
    showStepCounter?: boolean | "true" | "false";
    labels?: any;
    stepCounterText?: string;
    ariaLabel?: string;
  }
  interface KpRadioComponentJsx extends KpElementBaseAttributes {
    size?: 'sm' | 'md' | 'lg' | (string & {});
    color?: 'primary' | 'danger' | (string & {});
    value?: string;
    checked?: boolean | "true" | "false";
    disabled?: boolean | "true" | "false";
    required?: boolean | "true" | "false";
    name?: string;
    forceState?: 'rest' | 'hover' | 'active' | 'focus' | 'disabled' | 'loading' | 'error' | (string & {}) | null;
    hasLabel?: boolean | "true" | "false";
    ariaLabel?: string;
  }
  interface KpRadioGroupComponentJsx extends KpElementBaseAttributes {
    value?: string;
    name?: string;
    disabled?: boolean | "true" | "false";
    orientation?: 'vertical' | 'horizontal' | (string & {});
  }
  interface KpRichTextEditorComponentJsx extends KpElementBaseAttributes {
    size?: 'sm' | 'md' | 'lg' | (string & {});
    placeholder?: string;
    disabled?: boolean | "true" | "false";
    error?: boolean | "true" | "false";
    extensions?: 'default' | (string & {});
  }
  interface KpRowComponentJsx extends KpElementBaseAttributes {
    gap?: 'none' | '2xs' | 'xs' | 'sm' | 'md' | 'lg' | 'xl' | '2xl' | (string & {});
    align?: 'start' | 'center' | 'end' | 'stretch' | 'baseline' | (string & {});
    justify?: 'start' | 'center' | 'end' | 'space-between' | 'space-around' | (string & {});
    wrap?: boolean | "true" | "false";
  }
  interface KpSearchBarComponentJsx extends KpElementBaseAttributes {
    variant?: 'inline' | 'command-palette' | (string & {});
    size?: 'sm' | 'md' | 'lg' | (string & {});
    placeholder?: string;
    value?: string;
    showShortcutHint?: boolean | "true" | "false";
    shortcutHint?: string;
    groups?: any;
  }
  interface KpSegmentedControlComponentJsx extends KpElementBaseAttributes {
    size?: 'xs' | 'sm' | 'md' | 'lg' | 'xl' | (string & {});
    options?: any;
    display?: 'text' | 'icon' | 'icon-text' | (string & {});
    disabled?: boolean | "true" | "false";
    name?: string;
  }
  interface KpSelectComponentJsx extends KpElementBaseAttributes {
    size?: 'xs' | 'sm' | 'md' | 'lg' | 'xl' | (string & {});
    placeholder?: string;
    label?: string;
    floatingLabel?: boolean | "true" | "false";
    options?: any;
    multiple?: boolean | "true" | "false";
    showClear?: boolean | "true" | "false";
    disabled?: boolean | "true" | "false";
    required?: boolean | "true" | "false";
    name?: string;
    forceState?: 'rest' | 'hover' | 'active' | 'focus' | 'disabled' | 'loading' | 'error' | (string & {}) | null;
  }
  interface KpSettingsPanelComponentJsx extends KpElementBaseAttributes {
    size?: 'sm' | 'md' | 'lg' | (string & {});
    title?: string;
    description?: string;
    showHeader?: boolean | "true" | "false";
    showDescription?: boolean | "true" | "false";
    showOuterBorder?: boolean | "true" | "false";
  }
  interface KpSettingsRowComponentJsx extends KpElementBaseAttributes {
    size?: 'sm' | 'md' | 'lg' | (string & {});
    title?: string;
    description?: string;
    showDescription?: boolean | "true" | "false";
    showDivider?: boolean | "true" | "false";
  }
  interface KpSidebarComponentJsx extends KpElementBaseAttributes {
    widthState?: 'expanded' | 'collapsed' | (string & {});
    appearance?: 'light' | 'dark' | (string & {});
    persistKey?: string;
    showLogo?: boolean | "true" | "false";
    logoText?: string;
    showSearch?: boolean | "true" | "false";
    showSectionLabels?: boolean | "true" | "false";
    showUserFooter?: boolean | "true" | "false";
    sections?: any;
    userName?: string;
    userEmail?: string;
    userInitials?: string;
  }
  interface KpSkeletonComponentJsx extends KpElementBaseAttributes {
    shape?: 'line' | 'circle' | 'rectangle' | 'avatar' | 'button' | 'card' | (string & {});
    size?: 'xs' | 'sm' | 'md' | 'lg' | 'xl' | (string & {});
    animated?: boolean | "true" | "false";
    width?: string;
    height?: string;
  }
  interface KpSliderComponentJsx extends KpElementBaseAttributes {
    size?: 'sm' | 'md' | 'lg' | (string & {});
    mode?: 'single' | 'range' | (string & {});
    min?: number | string;
    max?: number | string;
    step?: number | string;
    showTicks?: boolean | "true" | "false";
    showValueLabel?: boolean | "true" | "false";
    showLabels?: boolean | "true" | "false";
    minLabel?: string;
    maxLabel?: string;
    ariaLabel?: string;
    ariaLabelStart?: string;
    ariaLabelEnd?: string;
    valueFormatter?: number | string;
  }
  interface KpStackComponentJsx extends KpElementBaseAttributes {
    gap?: 'none' | '2xs' | 'xs' | 'sm' | 'md' | 'lg' | 'xl' | '2xl' | (string & {});
    align?: 'start' | 'center' | 'end' | 'stretch' | (string & {});
  }
  interface KpStatCardComponentJsx extends KpElementBaseAttributes {
    size?: 'sm' | 'md' | 'lg' | (string & {});
    label?: string;
    value?: number | string;
    showIcon?: boolean | "true" | "false";
    icon?: string;
    showTrend?: boolean | "true" | "false";
    trendDirection?: 'up' | 'down' | 'neutral' | (string & {});
    trendAppearance?: 'positive' | 'negative' | (string & {});
    trendValue?: string;
    trendDescription?: string;
    showSparkline?: boolean | "true" | "false";
    sparklineData?: any;
  }
  interface KpTableComponentJsx extends KpElementBaseAttributes {
    size?: 'sm' | 'md' | 'lg' | (string & {});
    columns?: any;
    data?: any;
    striped?: boolean | "true" | "false";
    bordered?: boolean | "true" | "false";
    selectable?: boolean | "true" | "false";
    selected?: any;
    sort?: string;
    emptyMessage?: string;
    trackBy?: number | string;
  }
  interface KpTableToolbarComponentJsx extends KpElementBaseAttributes {
    mode?: 'default' | 'bulk-select' | (string & {});
    showSearch?: boolean | "true" | "false";
    searchPlaceholder?: string;
    searchValue?: string;
    showFilter?: boolean | "true" | "false";
    activeFilterCount?: number | string;
    showSort?: boolean | "true" | "false";
    showDensity?: boolean | "true" | "false";
    density?: 'compact' | 'comfortable' | 'spacious' | (string & {});
    showColumnPicker?: boolean | "true" | "false";
    showExport?: boolean | "true" | "false";
    showCreate?: boolean | "true" | "false";
    createLabel?: string;
    selectedCount?: number | string;
  }
  interface KpTableVirtualComponentJsx extends KpElementBaseAttributes {
    columns?: any;
    data?: any;
    size?: 'sm' | 'md' | 'lg' | (string & {});
    rowHeight?: number | string;
    viewportHeight?: number | string;
    overscan?: number | string;
    striped?: boolean | "true" | "false";
    bordered?: boolean | "true" | "false";
    ariaLabel?: string;
    trackBy?: number | string;
  }
  interface KpTabsComponentJsx extends KpElementBaseAttributes {
    size?: 'sm' | 'md' | 'lg' | (string & {});
    fullWidth?: boolean | "true" | "false";
  }
  interface KpTextareaComponentJsx extends KpElementBaseAttributes {
    size?: 'sm' | 'md' | 'lg' | (string & {});
    placeholder?: string;
    rows?: number | string;
    maxLength?: number | string;
    showCounter?: boolean | "true" | "false";
    resize?: 'both' | 'vertical' | 'horizontal' | 'none' | (string & {});
    filled?: boolean | "true" | "false";
    disabled?: boolean | "true" | "false";
    forceState?: 'rest' | 'hover' | 'active' | 'focus' | 'disabled' | 'loading' | 'error' | (string & {}) | null;
    ariaLabel?: string;
  }
  interface KpThemeToggleComponentJsx extends KpElementBaseAttributes {
    variant?: 'icon' | 'segmented' | 'dropdown' | (string & {});
    size?: 'sm' | 'md' | 'lg' | (string & {});
    currentTheme?: 'light' | 'dark' | 'system' | (string & {});
    showLabel?: boolean | "true" | "false";
  }
  interface KpTimePickerComponentJsx extends KpElementBaseAttributes {
    size?: 'sm' | 'md' | 'lg' | (string & {});
    format?: '12h' | '24h' | 'auto' | (string & {});
    showSeconds?: boolean | "true" | "false";
    minuteStep?: number | string;
    secondStep?: number | string;
    placeholder?: string;
    showClear?: boolean | "true" | "false";
    disabled?: boolean | "true" | "false";
    forceState?: 'rest' | 'hover' | 'active' | 'focus' | 'disabled' | 'loading' | 'error' | (string & {}) | null;
  }
  interface KpToastHostComponentJsx extends KpElementBaseAttributes {
    position?: 'top-right' | 'top-left' | 'bottom-right' | 'bottom-left' | (string & {});
    size?: 'sm' | 'md' | (string & {});
    showIcon?: boolean | "true" | "false";
    max?: number | string;
  }
  interface KpToggleComponentJsx extends KpElementBaseAttributes {
    size?: 'sm' | 'md' | 'lg' | (string & {});
    color?: 'primary' | 'danger' | (string & {});
    on?: boolean | "true" | "false";
    disabled?: boolean | "true" | "false";
    required?: boolean | "true" | "false";
    name?: string;
    value?: string;
    forceState?: 'rest' | 'hover' | 'active' | 'focus' | 'disabled' | 'loading' | 'error' | (string & {}) | null;
    hasLabel?: boolean | "true" | "false";
    ariaLabel?: string;
  }
  interface KpTreeComponentJsx extends KpElementBaseAttributes {
    size?: 'sm' | 'md' | (string & {});
    data?: any;
    showIcons?: boolean | "true" | "false";
    showCheckboxes?: boolean | "true" | "false";
    expanded?: any;
    selected?: string;
    checked?: any;
  }
  interface KpUserMenuComponentJsx extends KpElementBaseAttributes {
    size?: 'sm' | 'md' | (string & {});
    userName?: string;
    userEmail?: string;
    userInitials?: string;
    presence?: 'online' | 'offline' | 'busy' | 'away' | (string & {}) | null;
    showEmail?: boolean | "true" | "false";
    showPlanBadge?: boolean | "true" | "false";
    planName?: string;
    showThemeToggle?: boolean | "true" | "false";
    showHelpLink?: boolean | "true" | "false";
  }
  interface KpVirtualListComponentJsx extends KpElementBaseAttributes {
    items?: any;
    itemHeight?: number | string;
    viewportHeight?: number | string;
    overscan?: number | string;
    trackBy?: number | string;
  }

  namespace JSX {
    interface IntrinsicElements {
      'kp-accordion': KpAccordionComponentJsx;
      'kp-accordion-item': KpAccordionItemComponentJsx;
      'kp-alert': KpAlertComponentJsx;
      'kp-app-shell': KpAppShellComponentJsx;
      'kp-avatar': KpAvatarComponentJsx;
      'kp-avatar-group': KpAvatarGroupComponentJsx;
      'kp-badge': KpBadgeComponentJsx;
      'kp-banner': KpBannerComponentJsx;
      'kp-breadcrumb-item': KpBreadcrumbItemComponentJsx;
      'kp-breadcrumb-separator': KpBreadcrumbSeparatorComponentJsx;
      'kp-breadcrumbs': KpBreadcrumbsComponentJsx;
      'kp-breadcrumbs-auto': KpBreadcrumbsAutoComponentJsx;
      'kp-card': KpCardComponentJsx;
      'kp-checkbox': KpCheckboxComponentJsx;
      'kp-combobox': KpComboboxComponentJsx;
      'kp-command-palette': KpCommandPaletteComponentJsx;
      'kp-container': KpContainerComponentJsx;
      'kp-date-picker': KpDatePickerComponentJsx;
      'kp-dialog': KpDialogComponentJsx;
      'kp-divider': KpDividerComponentJsx;
      'kp-drawer': KpDrawerComponentJsx;
      'kp-dropdown-menu': KpDropdownMenuComponentJsx;
      'kp-empty-state': KpEmptyStateComponentJsx;
      'kp-file-upload': KpFileUploadComponentJsx;
      'kp-filter-bar': KpFilterBarComponentJsx;
      'kp-form-field': KpFormFieldComponentJsx;
      'kp-form-section': KpFormSectionComponentJsx;
      'kp-grid': KpGridComponentJsx;
      'kp-header': KpHeaderComponentJsx;
      'kp-icon': KpIconComponentJsx;
      'kp-icon-button': KpIconButtonComponentJsx;
      'kp-input': KpInputComponentJsx;
      'kp-markdown-viewer': KpMarkdownViewerComponentJsx;
      'kp-menu-divider': KpMenuDividerComponentJsx;
      'kp-menu-item': KpMenuItemComponentJsx;
      'kp-menu-section-label': KpMenuSectionLabelComponentJsx;
      'kp-nav-item': KpNavItemComponentJsx;
      'kp-notification-center': KpNotificationCenterComponentJsx;
      'kp-notification-item': KpNotificationItemComponentJsx;
      'kp-number-stepper': KpNumberStepperComponentJsx;
      'kp-page-error': KpPageErrorComponentJsx;
      'kp-page-header': KpPageHeaderComponentJsx;
      'kp-pagination': KpPaginationComponentJsx;
      'kp-pagination-item': KpPaginationItemComponentJsx;
      'kp-popover': KpPopoverComponentJsx;
      'kp-progress-circular': KpProgressCircularComponentJsx;
      'kp-progress-linear': KpProgressLinearComponentJsx;
      'kp-progress-segmented': KpProgressSegmentedComponentJsx;
      'kp-radio': KpRadioComponentJsx;
      'kp-radio-group': KpRadioGroupComponentJsx;
      'kp-rich-text-editor': KpRichTextEditorComponentJsx;
      'kp-row': KpRowComponentJsx;
      'kp-search-bar': KpSearchBarComponentJsx;
      'kp-segmented-control': KpSegmentedControlComponentJsx;
      'kp-select': KpSelectComponentJsx;
      'kp-settings-panel': KpSettingsPanelComponentJsx;
      'kp-settings-row': KpSettingsRowComponentJsx;
      'kp-sidebar': KpSidebarComponentJsx;
      'kp-skeleton': KpSkeletonComponentJsx;
      'kp-slider': KpSliderComponentJsx;
      'kp-stack': KpStackComponentJsx;
      'kp-stat-card': KpStatCardComponentJsx;
      'kp-table': KpTableComponentJsx;
      'kp-table-toolbar': KpTableToolbarComponentJsx;
      'kp-table-virtual': KpTableVirtualComponentJsx;
      'kp-tabs': KpTabsComponentJsx;
      'kp-textarea': KpTextareaComponentJsx;
      'kp-theme-toggle': KpThemeToggleComponentJsx;
      'kp-time-picker': KpTimePickerComponentJsx;
      'kp-toast-host': KpToastHostComponentJsx;
      'kp-toggle': KpToggleComponentJsx;
      'kp-tree': KpTreeComponentJsx;
      'kp-user-menu': KpUserMenuComponentJsx;
      'kp-virtual-list': KpVirtualListComponentJsx;
    }
  }
}

export {};
