// AUTO-GENERATED by scripts/generate-elements-registry.js — do not edit.
// 74 element-selector components across 61 entry points.
import type { Type } from '@angular/core';
import { KpAccordionComponent, KpAccordionItemComponent } from '@kanso-protocol/ui/accordion';
import { KpAlertComponent } from '@kanso-protocol/ui/alert';
import { KpAppShellComponent } from '@kanso-protocol/ui/app-shell';
import { KpAvatarComponent } from '@kanso-protocol/ui/avatar';
import { KpAvatarGroupComponent } from '@kanso-protocol/ui/avatar-group';
import { KpBadgeComponent } from '@kanso-protocol/ui/badge';
import { KpBannerComponent } from '@kanso-protocol/ui/banner';
import { KpBreadcrumbItemComponent, KpBreadcrumbSeparatorComponent, KpBreadcrumbsAutoComponent, KpBreadcrumbsComponent } from '@kanso-protocol/ui/breadcrumbs';
import { KpIconButtonComponent } from '@kanso-protocol/ui/button';
import { KpCardComponent } from '@kanso-protocol/ui/card';
import { KpCheckboxComponent } from '@kanso-protocol/ui/checkbox';
import { KpComboboxComponent } from '@kanso-protocol/ui/combobox';
import { KpCommandPaletteComponent } from '@kanso-protocol/ui/command-palette';
import { KpContainerComponent } from '@kanso-protocol/ui/container';
import { KpDatePickerComponent } from '@kanso-protocol/ui/datepicker';
import { KpDialogComponent } from '@kanso-protocol/ui/dialog';
import { KpDividerComponent } from '@kanso-protocol/ui/divider';
import { KpDrawerComponent } from '@kanso-protocol/ui/drawer';
import { KpEmptyStateComponent } from '@kanso-protocol/ui/empty-state';
import { KpFileUploadComponent } from '@kanso-protocol/ui/file-upload';
import { KpFilterBarComponent } from '@kanso-protocol/ui/filter-bar';
import { KpFormFieldComponent } from '@kanso-protocol/ui/form-field';
import { KpFormSectionComponent } from '@kanso-protocol/ui/form-section';
import { KpGridComponent } from '@kanso-protocol/ui/grid';
import { KpHeaderComponent } from '@kanso-protocol/ui/header';
import { KpIconComponent } from '@kanso-protocol/ui/icon';
import { KpInputComponent } from '@kanso-protocol/ui/input';
import { KpMarkdownViewerComponent } from '@kanso-protocol/ui/markdown-viewer';
import { KpDropdownMenuComponent, KpMenuDividerComponent, KpMenuItemComponent, KpMenuSectionLabelComponent } from '@kanso-protocol/ui/menu';
import { KpNavItemComponent } from '@kanso-protocol/ui/nav-item';
import { KpNotificationCenterComponent, KpNotificationItemComponent } from '@kanso-protocol/ui/notification-center';
import { KpNumberStepperComponent } from '@kanso-protocol/ui/number-stepper';
import { KpPageErrorComponent } from '@kanso-protocol/ui/page-error';
import { KpPageHeaderComponent } from '@kanso-protocol/ui/page-header';
import { KpPaginationComponent, KpPaginationItemComponent } from '@kanso-protocol/ui/pagination';
import { KpPopoverComponent } from '@kanso-protocol/ui/popover';
import { KpProgressCircularComponent, KpProgressLinearComponent, KpProgressSegmentedComponent } from '@kanso-protocol/ui/progress';
import { KpRadioComponent, KpRadioGroupComponent } from '@kanso-protocol/ui/radio';
import { KpRichTextEditorComponent } from '@kanso-protocol/ui/rich-text-editor';
import { KpRowComponent } from '@kanso-protocol/ui/row';
import { KpSearchBarComponent } from '@kanso-protocol/ui/search-bar';
import { KpSegmentedControlComponent } from '@kanso-protocol/ui/segmented-control';
import { KpSelectComponent } from '@kanso-protocol/ui/select';
import { KpSettingsPanelComponent, KpSettingsRowComponent } from '@kanso-protocol/ui/settings-panel';
import { KpSidebarComponent } from '@kanso-protocol/ui/sidebar';
import { KpSkeletonComponent } from '@kanso-protocol/ui/skeleton';
import { KpSliderComponent } from '@kanso-protocol/ui/slider';
import { KpStackComponent } from '@kanso-protocol/ui/stack';
import { KpStatCardComponent } from '@kanso-protocol/ui/stat-card';
import { KpTableComponent } from '@kanso-protocol/ui/table';
import { KpTableToolbarComponent } from '@kanso-protocol/ui/table-toolbar';
import { KpTableVirtualComponent } from '@kanso-protocol/ui/table-virtual';
import { KpTabsComponent } from '@kanso-protocol/ui/tabs';
import { KpTextareaComponent } from '@kanso-protocol/ui/textarea';
import { KpThemeToggleComponent } from '@kanso-protocol/ui/theme-toggle';
import { KpTimePickerComponent } from '@kanso-protocol/ui/timepicker';
import { KpToastHostComponent } from '@kanso-protocol/ui/toast';
import { KpToggleComponent } from '@kanso-protocol/ui/toggle';
import { KpTreeComponent } from '@kanso-protocol/ui/tree';
import { KpUserMenuComponent } from '@kanso-protocol/ui/user-menu';
import { KpVirtualListComponent } from '@kanso-protocol/ui/virtual-list';

export interface KansoElementDef {
  readonly tag: string;
  readonly component: Type<unknown>;
}

export const KANSO_ELEMENTS: readonly KansoElementDef[] = [
  { tag: 'kp-accordion', component: KpAccordionComponent },
  { tag: 'kp-accordion-item', component: KpAccordionItemComponent },
  { tag: 'kp-alert', component: KpAlertComponent },
  { tag: 'kp-app-shell', component: KpAppShellComponent },
  { tag: 'kp-avatar', component: KpAvatarComponent },
  { tag: 'kp-avatar-group', component: KpAvatarGroupComponent },
  { tag: 'kp-badge', component: KpBadgeComponent },
  { tag: 'kp-banner', component: KpBannerComponent },
  { tag: 'kp-breadcrumb-item', component: KpBreadcrumbItemComponent },
  { tag: 'kp-breadcrumb-separator', component: KpBreadcrumbSeparatorComponent },
  { tag: 'kp-breadcrumbs', component: KpBreadcrumbsComponent },
  { tag: 'kp-breadcrumbs-auto', component: KpBreadcrumbsAutoComponent },
  { tag: 'kp-card', component: KpCardComponent },
  { tag: 'kp-checkbox', component: KpCheckboxComponent },
  { tag: 'kp-combobox', component: KpComboboxComponent },
  { tag: 'kp-command-palette', component: KpCommandPaletteComponent },
  { tag: 'kp-container', component: KpContainerComponent },
  { tag: 'kp-date-picker', component: KpDatePickerComponent },
  { tag: 'kp-dialog', component: KpDialogComponent },
  { tag: 'kp-divider', component: KpDividerComponent },
  { tag: 'kp-drawer', component: KpDrawerComponent },
  { tag: 'kp-dropdown-menu', component: KpDropdownMenuComponent },
  { tag: 'kp-empty-state', component: KpEmptyStateComponent },
  { tag: 'kp-file-upload', component: KpFileUploadComponent },
  { tag: 'kp-filter-bar', component: KpFilterBarComponent },
  { tag: 'kp-form-field', component: KpFormFieldComponent },
  { tag: 'kp-form-section', component: KpFormSectionComponent },
  { tag: 'kp-grid', component: KpGridComponent },
  { tag: 'kp-header', component: KpHeaderComponent },
  { tag: 'kp-icon', component: KpIconComponent },
  { tag: 'kp-icon-button', component: KpIconButtonComponent },
  { tag: 'kp-input', component: KpInputComponent },
  { tag: 'kp-markdown-viewer', component: KpMarkdownViewerComponent },
  { tag: 'kp-menu-divider', component: KpMenuDividerComponent },
  { tag: 'kp-menu-item', component: KpMenuItemComponent },
  { tag: 'kp-menu-section-label', component: KpMenuSectionLabelComponent },
  { tag: 'kp-nav-item', component: KpNavItemComponent },
  { tag: 'kp-notification-center', component: KpNotificationCenterComponent },
  { tag: 'kp-notification-item', component: KpNotificationItemComponent },
  { tag: 'kp-number-stepper', component: KpNumberStepperComponent },
  { tag: 'kp-page-error', component: KpPageErrorComponent },
  { tag: 'kp-page-header', component: KpPageHeaderComponent },
  { tag: 'kp-pagination', component: KpPaginationComponent },
  { tag: 'kp-pagination-item', component: KpPaginationItemComponent },
  { tag: 'kp-popover', component: KpPopoverComponent },
  { tag: 'kp-progress-circular', component: KpProgressCircularComponent },
  { tag: 'kp-progress-linear', component: KpProgressLinearComponent },
  { tag: 'kp-progress-segmented', component: KpProgressSegmentedComponent },
  { tag: 'kp-radio', component: KpRadioComponent },
  { tag: 'kp-radio-group', component: KpRadioGroupComponent },
  { tag: 'kp-rich-text-editor', component: KpRichTextEditorComponent },
  { tag: 'kp-row', component: KpRowComponent },
  { tag: 'kp-search-bar', component: KpSearchBarComponent },
  { tag: 'kp-segmented-control', component: KpSegmentedControlComponent },
  { tag: 'kp-select', component: KpSelectComponent },
  { tag: 'kp-settings-panel', component: KpSettingsPanelComponent },
  { tag: 'kp-settings-row', component: KpSettingsRowComponent },
  { tag: 'kp-sidebar', component: KpSidebarComponent },
  { tag: 'kp-skeleton', component: KpSkeletonComponent },
  { tag: 'kp-slider', component: KpSliderComponent },
  { tag: 'kp-stack', component: KpStackComponent },
  { tag: 'kp-stat-card', component: KpStatCardComponent },
  { tag: 'kp-table', component: KpTableComponent },
  { tag: 'kp-table-toolbar', component: KpTableToolbarComponent },
  { tag: 'kp-table-virtual', component: KpTableVirtualComponent },
  { tag: 'kp-tabs', component: KpTabsComponent },
  { tag: 'kp-textarea', component: KpTextareaComponent },
  { tag: 'kp-theme-toggle', component: KpThemeToggleComponent },
  { tag: 'kp-time-picker', component: KpTimePickerComponent },
  { tag: 'kp-toast-host', component: KpToastHostComponent },
  { tag: 'kp-toggle', component: KpToggleComponent },
  { tag: 'kp-tree', component: KpTreeComponent },
  { tag: 'kp-user-menu', component: KpUserMenuComponent },
  { tag: 'kp-virtual-list', component: KpVirtualListComponent },
];
