#!/usr/bin/env node
/**
 * Kanso Protocol — Model Context Protocol server.
 *
 * Exposes the component / pattern / token catalog so an AI agent in Claude
 * Code / Cursor / VS Code can author Kanso UI without the developer having
 * to paste docs or sift through package READMEs.
 *
 * Transport: stdio. Launch via `npx @kanso-protocol/mcp`.
 * Manifest: ships next to the compiled JS (packages/mcp/manifest.json),
 * regenerated by `scripts/generate-mcp-manifest.js` on every build.
 */

import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';
import { z } from 'zod';

interface ComponentInput {
  name: string;
  type: string;
  default: string | null;
  description: string;
}

interface ComponentOutput {
  name: string;
  payload: string;
}

interface ComponentMeta {
  name: string;
  className: string;
  selector: string;
  layer: 'components' | 'patterns';
  package: string;
  description: string;
  examples: string[];
  inputs: ComponentInput[];
  outputs: ComponentOutput[];
  ariaRole: string | null;
  sizeRamp: string[];
  keyboardPatterns: string[];
  docsUrl: string;
  sourcePath: string;
}

interface TokenMeta {
  name: string;
  value: string;
  category: string;
  subPath: string;
}

interface Manifest {
  generatedAt: string;
  version: string;
  totals: { components: number; patterns: number; tokens: number };
  components: ComponentMeta[];
  patterns: ComponentMeta[];
  tokens: TokenMeta[];
}

function loadManifest(): Manifest {
  const here = dirname(fileURLToPath(import.meta.url));
  // When installed via npm, the manifest lives one level up (next to package.json).
  const candidates = [
    resolve(here, '..', 'manifest.json'),
    resolve(here, 'manifest.json'),
  ];
  for (const p of candidates) {
    try {
      return JSON.parse(readFileSync(p, 'utf8')) as Manifest;
    } catch {
      /* try next */
    }
  }
  throw new Error('manifest.json not found — run `node scripts/generate-mcp-manifest.js` first.');
}

function summarize(c: ComponentMeta) {
  return {
    name: c.name,
    selector: c.selector,
    package: c.package,
    summary: c.description.split('\n')[0] || '',
    ariaRole: c.ariaRole,
  };
}

const manifest = loadManifest();

const server = new McpServer(
  { name: 'kanso-protocol', version: manifest.version },
  {
    capabilities: {
      tools: {},
      resources: {},
    },
  },
);

// ─── Components ─────────────────────────────────────────────────────────

server.registerTool(
  'list_components',
  {
    title: 'List Kanso components',
    description: 'Return a compact list of every component in @kanso-protocol/* — one line per item with selector, package, ARIA role, and a one-line summary. Use this first to discover what exists before calling get_component for details.',
    inputSchema: {},
  },
  async () => ({
    content: [
      {
        type: 'text',
        text: JSON.stringify(manifest.components.map(summarize), null, 2),
      },
    ],
  }),
);

server.registerTool(
  'get_component',
  {
    title: 'Get one Kanso component',
    description: 'Full metadata for a single component: description, usage example, every @Input (name/type/default/description), every @Output with its payload type, ARIA role, detected keyboard patterns, and the Storybook docs URL. Accepts either the short name ("button") or the selector ("kp-button").',
    inputSchema: {
      name: z.string().describe('Component short name (e.g. "button") or selector (e.g. "kp-button")'),
    },
  },
  async ({ name }) => {
    const key = name.replace(/^kp-/, '').toLowerCase();
    const hit = manifest.components.find(
      (c) => c.name === key || c.selector === `kp-${key}` || c.className.toLowerCase() === `kp${key.replace(/-/g, '')}component`,
    );
    if (!hit) {
      return {
        content: [
          { type: 'text', text: `No component named "${name}". Call list_components to see available names.` },
        ],
        isError: true,
      };
    }
    return { content: [{ type: 'text', text: JSON.stringify(hit, null, 2) }] };
  },
);

// ─── Patterns ───────────────────────────────────────────────────────────

server.registerTool(
  'list_patterns',
  {
    title: 'List Kanso patterns',
    description: 'Patterns are larger compositions (page shells, layouts, bars) built from components — e.g. app-shell, page-header, filter-bar. Same shape as components in the manifest.',
    inputSchema: {},
  },
  async () => ({
    content: [{ type: 'text', text: JSON.stringify(manifest.patterns.map(summarize), null, 2) }],
  }),
);

server.registerTool(
  'get_pattern',
  {
    title: 'Get one Kanso pattern',
    description: 'Full metadata for a single pattern — inputs, outputs, description, docs URL.',
    inputSchema: {
      name: z.string().describe('Pattern short name (e.g. "page-header")'),
    },
  },
  async ({ name }) => {
    const key = name.replace(/^kp-/, '').toLowerCase();
    const hit = manifest.patterns.find((p) => p.name === key || p.selector === `kp-${key}`);
    if (!hit) {
      return {
        content: [{ type: 'text', text: `No pattern named "${name}". Call list_patterns to see available names.` }],
        isError: true,
      };
    }
    return { content: [{ type: 'text', text: JSON.stringify(hit, null, 2) }] };
  },
);

// ─── Tokens ─────────────────────────────────────────────────────────────

server.registerTool(
  'list_tokens',
  {
    title: 'List Kanso design tokens',
    description: 'Return every CSS custom property from the built tokens.css. Optionally filter by category ("color" | "spacing" | "radius" | "motion" | "font" | …) or by a substring of the name.',
    inputSchema: {
      category: z.string().optional().describe('Top-level category (e.g. "color"). Omit to return all.'),
      contains: z.string().optional().describe('Case-insensitive substring to match anywhere in the token name.'),
    },
  },
  async ({ category, contains }) => {
    const needle = contains?.toLowerCase();
    const rows = manifest.tokens.filter((t) => {
      if (category && t.category !== category) return false;
      if (needle && !t.name.toLowerCase().includes(needle)) return false;
      return true;
    });
    return { content: [{ type: 'text', text: JSON.stringify(rows, null, 2) }] };
  },
);

server.registerTool(
  'get_token',
  {
    title: 'Get one Kanso token',
    description: 'Look up a single CSS variable. Accepts with or without the "--kp-" prefix.',
    inputSchema: {
      name: z.string().describe('Token name, with or without "--kp-" prefix (e.g. "color-blue-600" or "--kp-color-blue-600")'),
    },
  },
  async ({ name }) => {
    const normalized = name.startsWith('--kp-') ? name : `--kp-${name.replace(/^kp-/, '')}`;
    const hit = manifest.tokens.find((t) => t.name === normalized);
    if (!hit) {
      return {
        content: [{ type: 'text', text: `No token named "${normalized}". Call list_tokens to discover.` }],
        isError: true,
      };
    }
    return { content: [{ type: 'text', text: JSON.stringify(hit, null, 2) }] };
  },
);

// ─── Top-level "index" resource ─────────────────────────────────────────

server.registerTool(
  'catalog_overview',
  {
    title: 'Catalog overview',
    description: 'One-shot summary: version, totals, and generation timestamp. Call once at session start to get a feel for what the MCP knows.',
    inputSchema: {},
  },
  async () => ({
    content: [
      {
        type: 'text',
        text: JSON.stringify({
          version: manifest.version,
          generatedAt: manifest.generatedAt,
          totals: manifest.totals,
          docs: 'https://gregnblack.github.io/kanso-protocol/',
          repo: 'https://github.com/GregNBlack/kanso-protocol',
        }, null, 2),
      },
    ],
  }),
);

// ─── Boot ───────────────────────────────────────────────────────────────

const transport = new StdioServerTransport();
await server.connect(transport);
