#!/usr/bin/env node
/**
 * Kanso Protocol — Model Context Protocol server.
 *
 * Exposes the component / pattern / token catalog so an AI agent in Claude
 * Code / Cursor / VS Code can author Kanso UI without the developer having
 * to paste docs or sift through package READMEs.
 *
 * Transport: stdio. Launch via `npx @kanso-protocol/mcp`.
 * Manifest: ships next to the compiled JS (packages/mcp/manifest.json),
 * regenerated by `scripts/generate-mcp-manifest.js` on every build.
 *
 * Implementation note — uses the low-level `Server` API rather than the
 * high-level `McpServer`. The latter infers tool input shapes through
 * deeply generic Zod plumbing, which trips TS's "Type instantiation is
 * excessively deep" check in CI. Hand-rolled JSON Schema avoids the
 * inference cost entirely and keeps the build deterministic.
 */

import { readFileSync } from 'node:fs';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { dirname, resolve } from 'node:path';

import { Server } from '@modelcontextprotocol/sdk/server/index.js';
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';
import {
  CallToolRequestSchema,
  ListToolsRequestSchema,
} from '@modelcontextprotocol/sdk/types.js';

interface ComponentInput {
  name: string;
  type: string;
  default: string | null;
  description: string;
}

interface ComponentOutput {
  name: string;
  payload: string;
}

interface FigmaRef {
  fileKey: string;
  nodeId: string;
  url: string;
}

interface CodeConnectRef {
  npm: string;
  primaryClass: string;
  selector: string;
  import: string;
  docs: string;
  storybook: string;
}

type Stability = 'stable' | 'beta' | 'experimental' | 'internal';

interface ComponentMeta {
  name: string;
  className: string;
  selector: string;
  /** Additional public selectors exported by the same folder (sub-directives). */
  subSelectors: string[];
  /** API stability tier, parsed from docs/stability.md; null when unlisted. */
  stability: Stability | null;
  layer: 'components' | 'patterns';
  package: string;
  description: string;
  examples: string[];
  inputs: ComponentInput[];
  outputs: ComponentOutput[];
  ariaRole: string | null;
  sizeRamp: string[];
  keyboardPatterns: string[];
  docsUrl: string;
  sourcePath: string;
  figma?: FigmaRef;
  codeConnect?: CodeConnectRef;
}

interface TokenMeta {
  name: string;
  value: string;
  category: string;
  subPath: string;
}

interface FigmaContext {
  fileKey: string;
  fileName: string;
  url: string;
  pages: Record<string, { id: string; name: string }>;
  // Optional: Tabler glyphs may be inlined into the main file, in which case
  // there is no separate library fileKey (only a $comment lives here).
  iconLibrary?: { fileKey?: string; name?: string };
  foundations: Record<string, string>;
}

interface Manifest {
  generatedAt: string;
  version: string;
  totals: { components: number; patterns: number; tokens: number };
  figma: FigmaContext | null;
  components: ComponentMeta[];
  patterns: ComponentMeta[];
  tokens: TokenMeta[];
}

function loadManifest(): Manifest {
  const here = dirname(fileURLToPath(import.meta.url));
  // When installed via npm, the manifest lives one level up (next to package.json).
  const candidates = [
    resolve(here, '..', 'manifest.json'),
    resolve(here, 'manifest.json'),
  ];
  for (const p of candidates) {
    try {
      return JSON.parse(readFileSync(p, 'utf8')) as Manifest;
    } catch {
      /* try next */
    }
  }
  throw new Error('manifest.json not found — run `node scripts/generate-mcp-manifest.js` first.');
}

/**
 * Resolve the Figma file context with environment-variable overrides:
 *   KANSO_FIGMA_FILE_KEY  — point at a forked / private Kanso file instead of
 *                           the canonical public one. Useful when a team
 *                           branches the system internally.
 *   KANSO_FIGMA_FILE_URL  — full URL override; rarely needed (auto-derived
 *                           from fileKey if missing).
 * If the manifest has no figma block (e.g., the mapping JSON wasn't shipped),
 * we return null and the bridge tools downgrade to a "not configured" error.
 */
function resolveFigma(fig: FigmaContext | null): FigmaContext | null {
  if (!fig) return null;
  const overrideKey = process.env.KANSO_FIGMA_FILE_KEY;
  const overrideUrl = process.env.KANSO_FIGMA_FILE_URL;
  if (!overrideKey && !overrideUrl) return fig;
  const fileKey = overrideKey ?? fig.fileKey;
  const url = overrideUrl ?? `https://www.figma.com/design/${fileKey}/Design-System`;
  return { ...fig, fileKey, url };
}

function nodeUrl(fileKey: string, nodeId: string): string {
  return `https://www.figma.com/design/${fileKey}/Design-System?node-id=${nodeId.replace(':', '-')}`;
}

function summarize(c: ComponentMeta) {
  return {
    name: c.name,
    selector: c.selector,
    package: c.package,
    stability: c.stability,
    summary: c.description.split('\n')[0] || '',
    ariaRole: c.ariaRole,
  };
}

/** Tally records by stability tier, e.g. { stable: 42, beta: 0 }. */
function stabilityBreakdown(records: ComponentMeta[]): Record<string, number> {
  const out: Record<string, number> = {};
  for (const r of records) {
    const tier = r.stability ?? 'unlisted';
    out[tier] = (out[tier] ?? 0) + 1;
  }
  return out;
}

const manifest = loadManifest();
const figma = resolveFigma(manifest.figma);

// ─── Tool registry ───────────────────────────────────────────────────────
// Hand-rolled JSON Schema for each tool. The MCP SDK serializes these to
// the client unchanged, so the LLM gets precise expectations without us
// running anything through Zod's inference layer.

interface ToolDef {
  name: string;
  title: string;
  description: string;
  inputSchema: Record<string, unknown>;
  handler: (args: Record<string, unknown>) => string | { error: string };
}

// Exported so the tool registry can be exercised in isolation (tests /
// verification harnesses) without spinning up the stdio transport.
export const tools: ToolDef[] = [
  {
    name: 'catalog_overview',
    title: 'Catalog overview',
    description: 'One-shot summary: version, totals, and generation timestamp. Call once at session start to get a feel for what the MCP knows.',
    inputSchema: { type: 'object', properties: {} },
    handler: () => JSON.stringify({
      version: manifest.version,
      generatedAt: manifest.generatedAt,
      totals: manifest.totals,
      stability: {
        components: stabilityBreakdown(manifest.components),
        patterns: stabilityBreakdown(manifest.patterns),
      },
      docs: 'https://gregnblack.github.io/kanso-protocol/',
      repo: 'https://github.com/GregNBlack/kanso-protocol',
    }, null, 2),
  },
  {
    name: 'list_components',
    title: 'List Kanso components',
    description: 'Return a compact list of every component in @kanso-protocol/* — one line per item with selector, package, ARIA role, and a one-line summary. Use this first to discover what exists before calling get_component for details.',
    inputSchema: { type: 'object', properties: {} },
    handler: () => JSON.stringify(manifest.components.map(summarize), null, 2),
  },
  {
    name: 'get_component',
    title: 'Get one Kanso component',
    description: 'Full metadata for a single component: description, usage example, every @Input (name/type/default/description), every @Output with its payload type, ARIA role, detected keyboard patterns, and the Storybook docs URL. Accepts either the short name ("button") or the selector ("kp-button").',
    inputSchema: {
      type: 'object',
      properties: {
        name: { type: 'string', description: 'Component short name (e.g. "button") or selector (e.g. "kp-button")' },
      },
      required: ['name'],
    },
    handler: (args) => {
      const raw = String(args.name ?? '');
      const key = raw.replace(/^kp-/, '').toLowerCase();
      const hit = manifest.components.find(
        (c) => c.name === key || c.selector === `kp-${key}` || c.className.toLowerCase() === `kp${key.replace(/-/g, '')}component`,
      );
      if (!hit) return { error: `No component named "${raw}". Call list_components to see available names.` };
      return JSON.stringify(hit, null, 2);
    },
  },
  {
    name: 'list_patterns',
    title: 'List Kanso patterns',
    description: 'Patterns are larger compositions (page shells, layouts, bars) built from components — e.g. app-shell, page-header, filter-bar. Same shape as components in the manifest.',
    inputSchema: { type: 'object', properties: {} },
    handler: () => JSON.stringify(manifest.patterns.map(summarize), null, 2),
  },
  {
    name: 'get_pattern',
    title: 'Get one Kanso pattern',
    description: 'Full metadata for a single pattern — inputs, outputs, description, docs URL.',
    inputSchema: {
      type: 'object',
      properties: { name: { type: 'string', description: 'Pattern short name (e.g. "page-header")' } },
      required: ['name'],
    },
    handler: (args) => {
      const raw = String(args.name ?? '');
      const key = raw.replace(/^kp-/, '').toLowerCase();
      const hit = manifest.patterns.find((p) => p.name === key || p.selector === `kp-${key}`);
      if (!hit) return { error: `No pattern named "${raw}". Call list_patterns to see available names.` };
      return JSON.stringify(hit, null, 2);
    },
  },
  {
    name: 'check_composition',
    title: 'Check a composition for contract violations',
    description:
      'Given a set of Kanso surfaces you intend to place together (one row / toolbar / form group) with the size you plan to use, flag design-contract violations a linter cannot catch — because they are runtime composition, not static CSS. Reports: (1) mixed sizes in the same composition (anatomy.md — an Input at md next to a Button at sm never lines up, since radius/padding/font-size scale together); (2) a size that is not in a surface\'s size ramp; (3) use of a beta / experimental surface (API may change). Advisory — call before composing UI to catch mismatches early.',
    inputSchema: {
      type: 'object',
      properties: {
        items: {
          type: 'array',
          description: 'Surfaces you intend to place together, each with the size you plan to use.',
          items: {
            type: 'object',
            properties: {
              component: { type: 'string', description: 'Short name or selector, e.g. "button" or "kp-input"' },
              size: { type: 'string', description: 'Chosen size, e.g. "md". Omit for surfaces with no size ramp.' },
            },
            required: ['component'],
          },
        },
      },
      required: ['items'],
    },
    handler: (args) => {
      const items = Array.isArray(args.items) ? (args.items as Array<Record<string, unknown>>) : null;
      if (!items || !items.length) return { error: 'Provide a non-empty `items` array of { component, size }.' };
      const violations: string[] = [];
      const warnings: string[] = [];
      const resolved: Array<{ name: string; size: string | null; sizeRamp: string[]; stability: Stability | null }> = [];
      for (const it of items) {
        const raw = String((it && it.component) ?? '');
        const key = raw.replace(/^kp-/, '').toLowerCase();
        const hit =
          manifest.components.find(
            (c) => c.name === key || c.selector === `kp-${key}` || c.className.toLowerCase() === `kp${key.replace(/-/g, '')}component`,
          ) || manifest.patterns.find((p) => p.name === key || p.selector === `kp-${key}`);
        if (!hit) {
          violations.push(`Unknown surface "${raw}" — call list_components / list_patterns to see valid names.`);
          continue;
        }
        const size = it && it.size != null ? String(it.size) : null;
        const ramp = hit.sizeRamp ?? [];
        if (size && ramp.length && !ramp.includes(size)) {
          violations.push(`${hit.name}: size "${size}" is not in its ramp [${ramp.join(', ')}].`);
        }
        if (hit.stability && hit.stability !== 'stable') {
          warnings.push(`${hit.name} is ${hit.stability} — its API may change; pin exact versions.`);
        }
        resolved.push({ name: hit.name, size, sizeRamp: ramp, stability: hit.stability });
      }
      // Mixed sizes in one composition — only among items that declared a size.
      const sizes = [...new Set(resolved.filter((r) => r.size).map((r) => r.size as string))];
      if (sizes.length > 1) {
        violations.push(
          `Mixed sizes in one composition: ${sizes.join(', ')}. Components placed together must share a single size — radius, padding, and font-size scale together (see docs/component-anatomy.md). Pick one size for the row.`,
        );
      }
      const ok = violations.length === 0;
      return JSON.stringify(
        { ok, verdict: ok ? (warnings.length ? 'ok with warnings' : 'ok') : 'contract violation', violations, warnings, resolved },
        null,
        2,
      );
    },
  },
  {
    name: 'list_tokens',
    title: 'List Kanso design tokens',
    description: 'Return every CSS custom property from the built tokens.css. Optionally filter by category ("color" | "spacing" | "radius" | "motion" | "font" | …) or by a substring of the name.',
    inputSchema: {
      type: 'object',
      properties: {
        category: { type: 'string', description: 'Top-level category (e.g. "color"). Omit to return all.' },
        contains: { type: 'string', description: 'Case-insensitive substring to match anywhere in the token name.' },
      },
    },
    handler: (args) => {
      const category = args.category ? String(args.category) : undefined;
      const needle = args.contains ? String(args.contains).toLowerCase() : undefined;
      const rows = manifest.tokens.filter((t) => {
        if (category && t.category !== category) return false;
        if (needle && !t.name.toLowerCase().includes(needle)) return false;
        return true;
      });
      return JSON.stringify(rows, null, 2);
    },
  },
  {
    name: 'get_token',
    title: 'Get one Kanso token',
    description: 'Look up a single CSS variable. Accepts with or without the "--kp-" prefix.',
    inputSchema: {
      type: 'object',
      properties: {
        name: { type: 'string', description: 'Token name, with or without "--kp-" prefix (e.g. "color-blue-600" or "--kp-color-blue-600")' },
      },
      required: ['name'],
    },
    handler: (args) => {
      const raw = String(args.name ?? '');
      const normalized = raw.startsWith('--kp-') ? raw : `--kp-${raw.replace(/^kp-/, '')}`;
      const hit = manifest.tokens.find((t) => t.name === normalized);
      if (!hit) return { error: `No token named "${normalized}". Call list_tokens to discover.` };
      return JSON.stringify(hit, null, 2);
    },
  },

  // ─── Figma bridge ─────────────────────────────────────────────────────
  // These tools return the Figma context the assistant needs to immediately
  // call the official Figma MCP (https://help.figma.com/hc/articles/32132100833559)
  // — `get_design_context`, `get_screenshot`, `get_variable_defs`, etc. —
  // without an extra discovery step. Each response includes:
  //   - fileKey + nodeId          (feed straight into the Figma MCP)
  //   - url                       (clickable link for the human in the loop)
  //   - relatedFigmaTools         (which Figma MCP tools to chain next)
  // The default file key points at the canonical public Kanso Design System
  // file. Override with KANSO_FIGMA_FILE_KEY env var when working off a fork.
  {
    name: 'figma_context',
    title: 'Figma library context',
    description: 'Top-level Figma metadata: canonical Design System file key + URL, page IDs (Components / Patterns / Foundations / Examples), and the linked Tabler icon library file. Call once when starting Figma-aware work so subsequent tools have the right fileKey to target.',
    inputSchema: { type: 'object', properties: {} },
    handler: () => {
      if (!figma) {
        return { error: 'Figma bridge is not configured. The manifest was generated without a figma-mapping.json — re-run `npm run generate:mcp-manifest` after copying the mapping into the package.' };
      }
      return JSON.stringify({
        fileKey: figma.fileKey,
        fileName: figma.fileName,
        url: figma.url,
        pages: figma.pages,
        iconLibrary: figma.iconLibrary,
        foundationsPages: Object.entries(figma.foundations).map(([key, nodeId]) => ({
          name: key,
          nodeId,
          url: nodeUrl(figma.fileKey, nodeId),
        })),
        notes: [
          'Pass fileKey to Figma MCP tools (get_design_context, get_screenshot, get_variable_defs).',
          'KANSO_FIGMA_FILE_KEY env var overrides the canonical key when working from a fork.',
        ],
      }, null, 2);
    },
  },
  {
    name: 'figma_for_component',
    title: 'Figma node for a Kanso component',
    description: 'Resolve a Kanso component name to its master frame in the Figma library. Returns fileKey + nodeId you feed into the Figma MCP\'s get_design_context (for code-and-screenshot) or get_screenshot (for a flat preview).',
    inputSchema: {
      type: 'object',
      properties: {
        name: { type: 'string', description: 'Component short name (e.g. "button") or selector (e.g. "kp-button")' },
      },
      required: ['name'],
    },
    handler: (args) => {
      if (!figma) return { error: 'Figma bridge is not configured.' };
      const raw = String(args.name ?? '');
      const key = raw.replace(/^kp-/, '').toLowerCase();
      const hit = manifest.components.find(
        (c) => c.name === key || c.selector === `kp-${key}` || c.className.toLowerCase() === `kp${key.replace(/-/g, '')}component`,
      );
      if (!hit) return { error: `No component named "${raw}". Call list_components to see available names.` };
      if (!hit.figma) {
        // Graceful, non-error result: the component is real but no Figma node
        // is mapped yet. We deliberately return null rather than guess a node
        // ID so the bridge never points the agent at the WRONG frame.
        return JSON.stringify({
          component: hit.name,
          package: hit.package,
          figmaNode: null,
          message: `No Figma node mapped yet for component "${hit.name}". Use the codeConnect import below; to add a Figma frame, map it in packages/mcp/figma-mapping.json and regenerate the manifest.`,
          codeConnect: hit.codeConnect ?? null,
        }, null, 2);
      }
      return JSON.stringify({
        component: hit.name,
        package: hit.package,
        fileKey: figma.fileKey,
        nodeId: hit.figma.nodeId,
        url: nodeUrl(figma.fileKey, hit.figma.nodeId),
        codeConnect: hit.codeConnect ?? null,
        relatedFigmaTools: [
          { tool: 'get_design_context', purpose: 'Pull the master frame as code + screenshot.' },
          { tool: 'get_screenshot',     purpose: 'Plain PNG of the master frame (no code).' },
          { tool: 'get_variable_defs',  purpose: 'List the CSS variables this frame consumes.' },
        ],
      }, null, 2);
    },
  },
  {
    name: 'figma_for_pattern',
    title: 'Figma node for a Kanso pattern',
    description: 'Same shape as figma_for_component but resolves higher-level patterns (app-shell, page-header, sidebar, …).',
    inputSchema: {
      type: 'object',
      properties: { name: { type: 'string', description: 'Pattern short name (e.g. "page-header")' } },
      required: ['name'],
    },
    handler: (args) => {
      if (!figma) return { error: 'Figma bridge is not configured.' };
      const raw = String(args.name ?? '');
      const key = raw.replace(/^kp-/, '').toLowerCase();
      const hit = manifest.patterns.find((p) => p.name === key || p.selector === `kp-${key}`);
      if (!hit) return { error: `No pattern named "${raw}". Call list_patterns to see available names.` };
      if (!hit.figma) {
        // Graceful, non-error result — real pattern, no Figma node mapped yet.
        return JSON.stringify({
          pattern: hit.name,
          package: hit.package,
          figmaNode: null,
          message: `No Figma node mapped yet for pattern "${hit.name}". Use the codeConnect import below; to add a Figma frame, map it in packages/mcp/figma-mapping.json and regenerate the manifest.`,
          codeConnect: hit.codeConnect ?? null,
        }, null, 2);
      }
      return JSON.stringify({
        pattern: hit.name,
        package: hit.package,
        fileKey: figma.fileKey,
        nodeId: hit.figma.nodeId,
        url: nodeUrl(figma.fileKey, hit.figma.nodeId),
        codeConnect: hit.codeConnect ?? null,
      }, null, 2);
    },
  },
  {
    name: 'figma_for_icon',
    title: 'Figma context for the icon library',
    description: 'Returns the Tabler Icon Pack file context — separate from the main Design System file. The Kanso Icon component wraps an instance from this library, so any glyph the assistant might want to insert lives there. Pass `query` to receive a search hint the assistant feeds into Figma MCP\'s search_design_system tool.',
    inputSchema: {
      type: 'object',
      properties: {
        query: { type: 'string', description: 'Optional icon name or concept (e.g. "search", "trash"). The response includes a searchQuery + library key the agent can use with Figma MCP\'s search_design_system.' },
      },
    },
    handler: (args) => {
      const query = args.query ? String(args.query).trim() : null;
      // Graceful, non-error result when no external icon library file is mapped.
      // Tabler glyphs are now inlined into the main Design System file (see the
      // figma-mapping.json iconLibrary note), so there is no separate fileKey to
      // hand back — returning null beats pointing the agent at an undefined key.
      if (!figma?.iconLibrary?.fileKey) {
        return JSON.stringify({
          fileKey: null,
          message: 'No standalone Figma icon library mapped yet. Tabler glyphs are inlined into the main Design System file; call figma_context for its fileKey, then use Figma MCP\'s search_design_system to find a glyph by name.',
          suggestedSearchQuery: query,
          designSystemFileKey: figma?.fileKey ?? null,
        }, null, 2);
      }
      return JSON.stringify({
        fileKey: figma.iconLibrary.fileKey,
        libraryName: figma.iconLibrary.name ?? 'Icons',
        url: `https://www.figma.com/design/${figma.iconLibrary.fileKey}/${encodeURIComponent(figma.iconLibrary.name ?? 'Icons')}`,
        suggestedSearchQuery: query,
        relatedFigmaTools: [
          { tool: 'search_design_system', purpose: 'Find the icon by name across the Tabler Icon Pack.' },
          { tool: 'get_libraries',        purpose: 'Confirm the library is subscribed in the target file.' },
        ],
        usageNote: 'In Kanso, every icon slot expects an instance of an Icon-component wrapper, not a raw Tabler glyph. Find the Tabler glyph here, then wrap it via the Kanso `kp-icon` component (see get_component name="icon" if it exists, otherwise the icon slot in the parent component\'s docs).',
      }, null, 2);
    },
  },
];

// ─── Wire up the server ─────────────────────────────────────────────────

const server = new Server(
  { name: 'kanso-protocol', version: manifest.version },
  { capabilities: { tools: {} } },
);

server.setRequestHandler(ListToolsRequestSchema, async () => ({
  tools: tools.map(({ name, title, description, inputSchema }) => ({
    name,
    title,
    description,
    inputSchema,
  })),
}));

server.setRequestHandler(CallToolRequestSchema, async (req) => {
  const tool = tools.find((t) => t.name === req.params.name);
  if (!tool) {
    return {
      content: [{ type: 'text', text: `Unknown tool: ${req.params.name}` }],
      isError: true,
    };
  }
  const args = (req.params.arguments ?? {}) as Record<string, unknown>;
  const result = tool.handler(args);
  if (typeof result === 'object' && result && 'error' in result) {
    return { content: [{ type: 'text', text: result.error }], isError: true };
  }
  return { content: [{ type: 'text', text: result as string }] };
});

// Only attach the stdio transport when run as the CLI entry point (the
// `kanso-mcp` bin / `node dist/index.js`). When the module is imported — e.g.
// by a test harness that exercises `tools` directly — we skip connect() so it
// doesn't block on stdin.
const invokedPath = process.argv[1] ? pathToFileURL(process.argv[1]).href : '';
if (import.meta.url === invokedPath) {
  const transport = new StdioServerTransport();
  await server.connect(transport);
}
