// AUTO-GENERATED by scripts/generate-elements-registry.js — do not edit.
import { KpAccordionComponent } from '@kanso-protocol/ui/accordion';
import { defineKansoElement } from '../runtime';

/** Register just the `<kp-accordion>` custom element. Idempotent. */
export function defineKpAccordion(): Promise<void> {
  return defineKansoElement('kp-accordion', KpAccordionComponent);
}

// Side-effect: importing this entry auto-registers the element, mirroring the
// all-in-one bundle (`import '@kanso-protocol/elements/accordion'`).
if (typeof customElements !== 'undefined') {
  void defineKpAccordion();
}
