// AUTO-GENERATED by scripts/generate-elements-registry.js — do not edit.
import { KpAccordionItemComponent } from '@kanso-protocol/ui/accordion';
import { defineKansoElement } from '../runtime';

/** Register just the `<kp-accordion-item>` custom element. Idempotent. */
export function defineKpAccordionItem(): Promise<void> {
  return defineKansoElement('kp-accordion-item', KpAccordionItemComponent);
}

// Side-effect: importing this entry auto-registers the element, mirroring the
// all-in-one bundle (`import '@kanso-protocol/elements/accordion-item'`).
if (typeof customElements !== 'undefined') {
  void defineKpAccordionItem();
}
