// AUTO-GENERATED by scripts/generate-elements-registry.js — do not edit.
import { KpAlertComponent } from '@kanso-protocol/ui/alert';
import { defineKansoElement } from '../runtime';

/** Register just the `<kp-alert>` custom element. Idempotent. */
export function defineKpAlert(): Promise<void> {
  return defineKansoElement('kp-alert', KpAlertComponent);
}

// Side-effect: importing this entry auto-registers the element, mirroring the
// all-in-one bundle (`import '@kanso-protocol/elements/alert'`).
if (typeof customElements !== 'undefined') {
  void defineKpAlert();
}
