// AUTO-GENERATED by scripts/generate-elements-registry.js — do not edit.
import { KpAppShellComponent } from '@kanso-protocol/ui/app-shell';
import { defineKansoElement } from '../runtime';

/** Register just the `<kp-app-shell>` custom element. Idempotent. */
export function defineKpAppShell(): Promise<void> {
  return defineKansoElement('kp-app-shell', KpAppShellComponent);
}

// Side-effect: importing this entry auto-registers the element, mirroring the
// all-in-one bundle (`import '@kanso-protocol/elements/app-shell'`).
if (typeof customElements !== 'undefined') {
  void defineKpAppShell();
}
