// AUTO-GENERATED by scripts/generate-elements-registry.js — do not edit.
import { KpAvatarComponent } from '@kanso-protocol/ui/avatar';
import { defineKansoElement } from '../runtime';

/** Register just the `<kp-avatar>` custom element. Idempotent. */
export function defineKpAvatar(): Promise<void> {
  return defineKansoElement('kp-avatar', KpAvatarComponent);
}

// Side-effect: importing this entry auto-registers the element, mirroring the
// all-in-one bundle (`import '@kanso-protocol/elements/avatar'`).
if (typeof customElements !== 'undefined') {
  void defineKpAvatar();
}
