// AUTO-GENERATED by scripts/generate-elements-registry.js — do not edit.
import { KpAvatarGroupComponent } from '@kanso-protocol/ui/avatar-group';
import { defineKansoElement } from '../runtime';

/** Register just the `<kp-avatar-group>` custom element. Idempotent. */
export function defineKpAvatarGroup(): Promise<void> {
  return defineKansoElement('kp-avatar-group', KpAvatarGroupComponent);
}

// Side-effect: importing this entry auto-registers the element, mirroring the
// all-in-one bundle (`import '@kanso-protocol/elements/avatar-group'`).
if (typeof customElements !== 'undefined') {
  void defineKpAvatarGroup();
}
