// AUTO-GENERATED by scripts/generate-elements-registry.js — do not edit.
import { KpBadgeComponent } from '@kanso-protocol/ui/badge';
import { defineKansoElement } from '../runtime';

/** Register just the `<kp-badge>` custom element. Idempotent. */
export function defineKpBadge(): Promise<void> {
  return defineKansoElement('kp-badge', KpBadgeComponent);
}

// Side-effect: importing this entry auto-registers the element, mirroring the
// all-in-one bundle (`import '@kanso-protocol/elements/badge'`).
if (typeof customElements !== 'undefined') {
  void defineKpBadge();
}
