// AUTO-GENERATED by scripts/generate-elements-registry.js — do not edit.
import { KpBannerComponent } from '@kanso-protocol/ui/banner';
import { defineKansoElement } from '../runtime';

/** Register just the `<kp-banner>` custom element. Idempotent. */
export function defineKpBanner(): Promise<void> {
  return defineKansoElement('kp-banner', KpBannerComponent);
}

// Side-effect: importing this entry auto-registers the element, mirroring the
// all-in-one bundle (`import '@kanso-protocol/elements/banner'`).
if (typeof customElements !== 'undefined') {
  void defineKpBanner();
}
