// AUTO-GENERATED by scripts/generate-elements-registry.js — do not edit.
import { KpBreadcrumbsComponent } from '@kanso-protocol/ui/breadcrumbs';
import { defineKansoElement } from '../runtime';

/** Register just the `<kp-breadcrumbs>` custom element. Idempotent. */
export function defineKpBreadcrumbs(): Promise<void> {
  return defineKansoElement('kp-breadcrumbs', KpBreadcrumbsComponent);
}

// Side-effect: importing this entry auto-registers the element, mirroring the
// all-in-one bundle (`import '@kanso-protocol/elements/breadcrumbs'`).
if (typeof customElements !== 'undefined') {
  void defineKpBreadcrumbs();
}
