// AUTO-GENERATED by scripts/generate-elements-registry.js — do not edit.
import { KpBreadcrumbSeparatorComponent } from '@kanso-protocol/ui/breadcrumbs';
import { defineKansoElement } from '../runtime';

/** Register just the `<kp-breadcrumb-separator>` custom element. Idempotent. */
export function defineKpBreadcrumbSeparator(): Promise<void> {
  return defineKansoElement('kp-breadcrumb-separator', KpBreadcrumbSeparatorComponent);
}

// Side-effect: importing this entry auto-registers the element, mirroring the
// all-in-one bundle (`import '@kanso-protocol/elements/breadcrumb-separator'`).
if (typeof customElements !== 'undefined') {
  void defineKpBreadcrumbSeparator();
}
