// AUTO-GENERATED by scripts/generate-elements-registry.js — do not edit.
import { KpBreadcrumbsAutoComponent } from '@kanso-protocol/ui/breadcrumbs';
import { defineKansoElement } from '../runtime';

/** Register just the `<kp-breadcrumbs-auto>` custom element. Idempotent. */
export function defineKpBreadcrumbsAuto(): Promise<void> {
  return defineKansoElement('kp-breadcrumbs-auto', KpBreadcrumbsAutoComponent);
}

// Side-effect: importing this entry auto-registers the element, mirroring the
// all-in-one bundle (`import '@kanso-protocol/elements/breadcrumbs-auto'`).
if (typeof customElements !== 'undefined') {
  void defineKpBreadcrumbsAuto();
}
