// AUTO-GENERATED by scripts/generate-elements-registry.js — do not edit.
import { KpBreadcrumbItemComponent } from '@kanso-protocol/ui/breadcrumbs';
import { defineKansoElement } from '../runtime';

/** Register just the `<kp-breadcrumb-item>` custom element. Idempotent. */
export function defineKpBreadcrumbItem(): Promise<void> {
  return defineKansoElement('kp-breadcrumb-item', KpBreadcrumbItemComponent);
}

// Side-effect: importing this entry auto-registers the element, mirroring the
// all-in-one bundle (`import '@kanso-protocol/elements/breadcrumb-item'`).
if (typeof customElements !== 'undefined') {
  void defineKpBreadcrumbItem();
}
