// AUTO-GENERATED by scripts/generate-elements-registry.js — do not edit.
import { KpCardComponent } from '@kanso-protocol/ui/card';
import { defineKansoElement } from '../runtime';

/** Register just the `<kp-card>` custom element. Idempotent. */
export function defineKpCard(): Promise<void> {
  return defineKansoElement('kp-card', KpCardComponent);
}

// Side-effect: importing this entry auto-registers the element, mirroring the
// all-in-one bundle (`import '@kanso-protocol/elements/card'`).
if (typeof customElements !== 'undefined') {
  void defineKpCard();
}
