// AUTO-GENERATED by scripts/generate-elements-registry.js — do not edit.
import { KpCheckboxComponent } from '@kanso-protocol/ui/checkbox';
import { defineKansoElement } from '../runtime';

/** Register just the `<kp-checkbox>` custom element. Idempotent. */
export function defineKpCheckbox(): Promise<void> {
  return defineKansoElement('kp-checkbox', KpCheckboxComponent);
}

// Side-effect: importing this entry auto-registers the element, mirroring the
// all-in-one bundle (`import '@kanso-protocol/elements/checkbox'`).
if (typeof customElements !== 'undefined') {
  void defineKpCheckbox();
}
