// AUTO-GENERATED by scripts/generate-elements-registry.js — do not edit.
import { KpComboboxComponent } from '@kanso-protocol/ui/combobox';
import { defineKansoElement } from '../runtime';

/** Register just the `<kp-combobox>` custom element. Idempotent. */
export function defineKpCombobox(): Promise<void> {
  return defineKansoElement('kp-combobox', KpComboboxComponent);
}

// Side-effect: importing this entry auto-registers the element, mirroring the
// all-in-one bundle (`import '@kanso-protocol/elements/combobox'`).
if (typeof customElements !== 'undefined') {
  void defineKpCombobox();
}
