// AUTO-GENERATED by scripts/generate-elements-registry.js — do not edit.
import { KpCommandPaletteComponent } from '@kanso-protocol/ui/command-palette';
import { defineKansoElement } from '../runtime';

/** Register just the `<kp-command-palette>` custom element. Idempotent. */
export function defineKpCommandPalette(): Promise<void> {
  return defineKansoElement('kp-command-palette', KpCommandPaletteComponent);
}

// Side-effect: importing this entry auto-registers the element, mirroring the
// all-in-one bundle (`import '@kanso-protocol/elements/command-palette'`).
if (typeof customElements !== 'undefined') {
  void defineKpCommandPalette();
}
