// AUTO-GENERATED by scripts/generate-elements-registry.js — do not edit.
import { KpContainerComponent } from '@kanso-protocol/ui/container';
import { defineKansoElement } from '../runtime';

/** Register just the `<kp-container>` custom element. Idempotent. */
export function defineKpContainer(): Promise<void> {
  return defineKansoElement('kp-container', KpContainerComponent);
}

// Side-effect: importing this entry auto-registers the element, mirroring the
// all-in-one bundle (`import '@kanso-protocol/elements/container'`).
if (typeof customElements !== 'undefined') {
  void defineKpContainer();
}
