// AUTO-GENERATED by scripts/generate-elements-registry.js — do not edit.
import { KpDatePickerComponent } from '@kanso-protocol/ui/datepicker';
import { defineKansoElement } from '../runtime';

/** Register just the `<kp-date-picker>` custom element. Idempotent. */
export function defineKpDatePicker(): Promise<void> {
  return defineKansoElement('kp-date-picker', KpDatePickerComponent);
}

// Side-effect: importing this entry auto-registers the element, mirroring the
// all-in-one bundle (`import '@kanso-protocol/elements/date-picker'`).
if (typeof customElements !== 'undefined') {
  void defineKpDatePicker();
}
