// AUTO-GENERATED by scripts/generate-elements-registry.js — do not edit.
import { KpDialogComponent } from '@kanso-protocol/ui/dialog';
import { defineKansoElement } from '../runtime';

/** Register just the `<kp-dialog>` custom element. Idempotent. */
export function defineKpDialog(): Promise<void> {
  return defineKansoElement('kp-dialog', KpDialogComponent);
}

// Side-effect: importing this entry auto-registers the element, mirroring the
// all-in-one bundle (`import '@kanso-protocol/elements/dialog'`).
if (typeof customElements !== 'undefined') {
  void defineKpDialog();
}
