// AUTO-GENERATED by scripts/generate-elements-registry.js — do not edit.
import { KpDividerComponent } from '@kanso-protocol/ui/divider';
import { defineKansoElement } from '../runtime';

/** Register just the `<kp-divider>` custom element. Idempotent. */
export function defineKpDivider(): Promise<void> {
  return defineKansoElement('kp-divider', KpDividerComponent);
}

// Side-effect: importing this entry auto-registers the element, mirroring the
// all-in-one bundle (`import '@kanso-protocol/elements/divider'`).
if (typeof customElements !== 'undefined') {
  void defineKpDivider();
}
