// AUTO-GENERATED by scripts/generate-elements-registry.js — do not edit.
import { KpDrawerComponent } from '@kanso-protocol/ui/drawer';
import { defineKansoElement } from '../runtime';

/** Register just the `<kp-drawer>` custom element. Idempotent. */
export function defineKpDrawer(): Promise<void> {
  return defineKansoElement('kp-drawer', KpDrawerComponent);
}

// Side-effect: importing this entry auto-registers the element, mirroring the
// all-in-one bundle (`import '@kanso-protocol/elements/drawer'`).
if (typeof customElements !== 'undefined') {
  void defineKpDrawer();
}
