// AUTO-GENERATED by scripts/generate-elements-registry.js — do not edit.
import { KpDropdownMenuComponent } from '@kanso-protocol/ui/menu';
import { defineKansoElement } from '../runtime';

/** Register just the `<kp-dropdown-menu>` custom element. Idempotent. */
export function defineKpDropdownMenu(): Promise<void> {
  return defineKansoElement('kp-dropdown-menu', KpDropdownMenuComponent);
}

// Side-effect: importing this entry auto-registers the element, mirroring the
// all-in-one bundle (`import '@kanso-protocol/elements/dropdown-menu'`).
if (typeof customElements !== 'undefined') {
  void defineKpDropdownMenu();
}
