// AUTO-GENERATED by scripts/generate-elements-registry.js — do not edit.
import { KpEmptyStateComponent } from '@kanso-protocol/ui/empty-state';
import { defineKansoElement } from '../runtime';

/** Register just the `<kp-empty-state>` custom element. Idempotent. */
export function defineKpEmptyState(): Promise<void> {
  return defineKansoElement('kp-empty-state', KpEmptyStateComponent);
}

// Side-effect: importing this entry auto-registers the element, mirroring the
// all-in-one bundle (`import '@kanso-protocol/elements/empty-state'`).
if (typeof customElements !== 'undefined') {
  void defineKpEmptyState();
}
