// AUTO-GENERATED by scripts/generate-elements-registry.js — do not edit.
import { KpFileUploadComponent } from '@kanso-protocol/ui/file-upload';
import { defineKansoElement } from '../runtime';

/** Register just the `<kp-file-upload>` custom element. Idempotent. */
export function defineKpFileUpload(): Promise<void> {
  return defineKansoElement('kp-file-upload', KpFileUploadComponent);
}

// Side-effect: importing this entry auto-registers the element, mirroring the
// all-in-one bundle (`import '@kanso-protocol/elements/file-upload'`).
if (typeof customElements !== 'undefined') {
  void defineKpFileUpload();
}
