// AUTO-GENERATED by scripts/generate-elements-registry.js — do not edit.
import { KpFilterBarComponent } from '@kanso-protocol/ui/filter-bar';
import { defineKansoElement } from '../runtime';

/** Register just the `<kp-filter-bar>` custom element. Idempotent. */
export function defineKpFilterBar(): Promise<void> {
  return defineKansoElement('kp-filter-bar', KpFilterBarComponent);
}

// Side-effect: importing this entry auto-registers the element, mirroring the
// all-in-one bundle (`import '@kanso-protocol/elements/filter-bar'`).
if (typeof customElements !== 'undefined') {
  void defineKpFilterBar();
}
