// AUTO-GENERATED by scripts/generate-elements-registry.js — do not edit.
import { KpFormSectionComponent } from '@kanso-protocol/ui/form-section';
import { defineKansoElement } from '../runtime';

/** Register just the `<kp-form-section>` custom element. Idempotent. */
export function defineKpFormSection(): Promise<void> {
  return defineKansoElement('kp-form-section', KpFormSectionComponent);
}

// Side-effect: importing this entry auto-registers the element, mirroring the
// all-in-one bundle (`import '@kanso-protocol/elements/form-section'`).
if (typeof customElements !== 'undefined') {
  void defineKpFormSection();
}
