// AUTO-GENERATED by scripts/generate-elements-registry.js — do not edit.
import { KpFormFieldComponent } from '@kanso-protocol/ui/form-field';
import { defineKansoElement } from '../runtime';

/** Register just the `<kp-form-field>` custom element. Idempotent. */
export function defineKpFormField(): Promise<void> {
  return defineKansoElement('kp-form-field', KpFormFieldComponent);
}

// Side-effect: importing this entry auto-registers the element, mirroring the
// all-in-one bundle (`import '@kanso-protocol/elements/form-field'`).
if (typeof customElements !== 'undefined') {
  void defineKpFormField();
}
