// AUTO-GENERATED by scripts/generate-elements-registry.js — do not edit.
import { KpGridComponent } from '@kanso-protocol/ui/grid';
import { defineKansoElement } from '../runtime';

/** Register just the `<kp-grid>` custom element. Idempotent. */
export function defineKpGrid(): Promise<void> {
  return defineKansoElement('kp-grid', KpGridComponent);
}

// Side-effect: importing this entry auto-registers the element, mirroring the
// all-in-one bundle (`import '@kanso-protocol/elements/grid'`).
if (typeof customElements !== 'undefined') {
  void defineKpGrid();
}
