// AUTO-GENERATED by scripts/generate-elements-registry.js — do not edit.
import { KpHeaderComponent } from '@kanso-protocol/ui/header';
import { defineKansoElement } from '../runtime';

/** Register just the `<kp-header>` custom element. Idempotent. */
export function defineKpHeader(): Promise<void> {
  return defineKansoElement('kp-header', KpHeaderComponent);
}

// Side-effect: importing this entry auto-registers the element, mirroring the
// all-in-one bundle (`import '@kanso-protocol/elements/header'`).
if (typeof customElements !== 'undefined') {
  void defineKpHeader();
}
