// AUTO-GENERATED by scripts/generate-elements-registry.js — do not edit.
import { KpIconComponent } from '@kanso-protocol/ui/icon';
import { defineKansoElement } from '../runtime';

/** Register just the `<kp-icon>` custom element. Idempotent. */
export function defineKpIcon(): Promise<void> {
  return defineKansoElement('kp-icon', KpIconComponent);
}

// Side-effect: importing this entry auto-registers the element, mirroring the
// all-in-one bundle (`import '@kanso-protocol/elements/icon'`).
if (typeof customElements !== 'undefined') {
  void defineKpIcon();
}
