// AUTO-GENERATED by scripts/generate-elements-registry.js — do not edit.
import { KpIconButtonComponent } from '@kanso-protocol/ui/button';
import { defineKansoElement } from '../runtime';

/** Register just the `<kp-icon-button>` custom element. Idempotent. */
export function defineKpIconButton(): Promise<void> {
  return defineKansoElement('kp-icon-button', KpIconButtonComponent);
}

// Side-effect: importing this entry auto-registers the element, mirroring the
// all-in-one bundle (`import '@kanso-protocol/elements/icon-button'`).
if (typeof customElements !== 'undefined') {
  void defineKpIconButton();
}
