// AUTO-GENERATED by scripts/generate-elements-registry.js — do not edit.
import { KpInputComponent } from '@kanso-protocol/ui/input';
import { defineKansoElement } from '../runtime';

/** Register just the `<kp-input>` custom element. Idempotent. */
export function defineKpInput(): Promise<void> {
  return defineKansoElement('kp-input', KpInputComponent);
}

// Side-effect: importing this entry auto-registers the element, mirroring the
// all-in-one bundle (`import '@kanso-protocol/elements/input'`).
if (typeof customElements !== 'undefined') {
  void defineKpInput();
}
