// AUTO-GENERATED by scripts/generate-elements-registry.js — do not edit.
import { KpMarkdownViewerComponent } from '@kanso-protocol/ui/markdown-viewer';
import { defineKansoElement } from '../runtime';

/** Register just the `<kp-markdown-viewer>` custom element. Idempotent. */
export function defineKpMarkdownViewer(): Promise<void> {
  return defineKansoElement('kp-markdown-viewer', KpMarkdownViewerComponent);
}

// Side-effect: importing this entry auto-registers the element, mirroring the
// all-in-one bundle (`import '@kanso-protocol/elements/markdown-viewer'`).
if (typeof customElements !== 'undefined') {
  void defineKpMarkdownViewer();
}
