// AUTO-GENERATED by scripts/generate-elements-registry.js — do not edit.
import { KpMenuDividerComponent } from '@kanso-protocol/ui/menu';
import { defineKansoElement } from '../runtime';

/** Register just the `<kp-menu-divider>` custom element. Idempotent. */
export function defineKpMenuDivider(): Promise<void> {
  return defineKansoElement('kp-menu-divider', KpMenuDividerComponent);
}

// Side-effect: importing this entry auto-registers the element, mirroring the
// all-in-one bundle (`import '@kanso-protocol/elements/menu-divider'`).
if (typeof customElements !== 'undefined') {
  void defineKpMenuDivider();
}
