// AUTO-GENERATED by scripts/generate-elements-registry.js — do not edit.
import { KpMenuItemComponent } from '@kanso-protocol/ui/menu';
import { defineKansoElement } from '../runtime';

/** Register just the `<kp-menu-item>` custom element. Idempotent. */
export function defineKpMenuItem(): Promise<void> {
  return defineKansoElement('kp-menu-item', KpMenuItemComponent);
}

// Side-effect: importing this entry auto-registers the element, mirroring the
// all-in-one bundle (`import '@kanso-protocol/elements/menu-item'`).
if (typeof customElements !== 'undefined') {
  void defineKpMenuItem();
}
