// AUTO-GENERATED by scripts/generate-elements-registry.js — do not edit.
import { KpNavItemComponent } from '@kanso-protocol/ui/nav-item';
import { defineKansoElement } from '../runtime';

/** Register just the `<kp-nav-item>` custom element. Idempotent. */
export function defineKpNavItem(): Promise<void> {
  return defineKansoElement('kp-nav-item', KpNavItemComponent);
}

// Side-effect: importing this entry auto-registers the element, mirroring the
// all-in-one bundle (`import '@kanso-protocol/elements/nav-item'`).
if (typeof customElements !== 'undefined') {
  void defineKpNavItem();
}
