// AUTO-GENERATED by scripts/generate-elements-registry.js — do not edit.
import { KpNotificationCenterComponent } from '@kanso-protocol/ui/notification-center';
import { defineKansoElement } from '../runtime';

/** Register just the `<kp-notification-center>` custom element. Idempotent. */
export function defineKpNotificationCenter(): Promise<void> {
  return defineKansoElement('kp-notification-center', KpNotificationCenterComponent);
}

// Side-effect: importing this entry auto-registers the element, mirroring the
// all-in-one bundle (`import '@kanso-protocol/elements/notification-center'`).
if (typeof customElements !== 'undefined') {
  void defineKpNotificationCenter();
}
