// AUTO-GENERATED by scripts/generate-elements-registry.js — do not edit.
import { KpNotificationItemComponent } from '@kanso-protocol/ui/notification-center';
import { defineKansoElement } from '../runtime';

/** Register just the `<kp-notification-item>` custom element. Idempotent. */
export function defineKpNotificationItem(): Promise<void> {
  return defineKansoElement('kp-notification-item', KpNotificationItemComponent);
}

// Side-effect: importing this entry auto-registers the element, mirroring the
// all-in-one bundle (`import '@kanso-protocol/elements/notification-item'`).
if (typeof customElements !== 'undefined') {
  void defineKpNotificationItem();
}
