// AUTO-GENERATED by scripts/generate-elements-registry.js — do not edit.
import { KpNumberStepperComponent } from '@kanso-protocol/ui/number-stepper';
import { defineKansoElement } from '../runtime';

/** Register just the `<kp-number-stepper>` custom element. Idempotent. */
export function defineKpNumberStepper(): Promise<void> {
  return defineKansoElement('kp-number-stepper', KpNumberStepperComponent);
}

// Side-effect: importing this entry auto-registers the element, mirroring the
// all-in-one bundle (`import '@kanso-protocol/elements/number-stepper'`).
if (typeof customElements !== 'undefined') {
  void defineKpNumberStepper();
}
