// AUTO-GENERATED by scripts/generate-elements-registry.js — do not edit.
import { KpPageHeaderComponent } from '@kanso-protocol/ui/page-header';
import { defineKansoElement } from '../runtime';

/** Register just the `<kp-page-header>` custom element. Idempotent. */
export function defineKpPageHeader(): Promise<void> {
  return defineKansoElement('kp-page-header', KpPageHeaderComponent);
}

// Side-effect: importing this entry auto-registers the element, mirroring the
// all-in-one bundle (`import '@kanso-protocol/elements/page-header'`).
if (typeof customElements !== 'undefined') {
  void defineKpPageHeader();
}
