// AUTO-GENERATED by scripts/generate-elements-registry.js — do not edit.
import { KpPageErrorComponent } from '@kanso-protocol/ui/page-error';
import { defineKansoElement } from '../runtime';

/** Register just the `<kp-page-error>` custom element. Idempotent. */
export function defineKpPageError(): Promise<void> {
  return defineKansoElement('kp-page-error', KpPageErrorComponent);
}

// Side-effect: importing this entry auto-registers the element, mirroring the
// all-in-one bundle (`import '@kanso-protocol/elements/page-error'`).
if (typeof customElements !== 'undefined') {
  void defineKpPageError();
}
