// AUTO-GENERATED by scripts/generate-elements-registry.js — do not edit.
import { KpPaginationComponent } from '@kanso-protocol/ui/pagination';
import { defineKansoElement } from '../runtime';

/** Register just the `<kp-pagination>` custom element. Idempotent. */
export function defineKpPagination(): Promise<void> {
  return defineKansoElement('kp-pagination', KpPaginationComponent);
}

// Side-effect: importing this entry auto-registers the element, mirroring the
// all-in-one bundle (`import '@kanso-protocol/elements/pagination'`).
if (typeof customElements !== 'undefined') {
  void defineKpPagination();
}
