// AUTO-GENERATED by scripts/generate-elements-registry.js — do not edit.
import { KpPaginationItemComponent } from '@kanso-protocol/ui/pagination';
import { defineKansoElement } from '../runtime';

/** Register just the `<kp-pagination-item>` custom element. Idempotent. */
export function defineKpPaginationItem(): Promise<void> {
  return defineKansoElement('kp-pagination-item', KpPaginationItemComponent);
}

// Side-effect: importing this entry auto-registers the element, mirroring the
// all-in-one bundle (`import '@kanso-protocol/elements/pagination-item'`).
if (typeof customElements !== 'undefined') {
  void defineKpPaginationItem();
}
