// AUTO-GENERATED by scripts/generate-elements-registry.js — do not edit.
import { KpPopoverComponent } from '@kanso-protocol/ui/popover';
import { defineKansoElement } from '../runtime';

/** Register just the `<kp-popover>` custom element. Idempotent. */
export function defineKpPopover(): Promise<void> {
  return defineKansoElement('kp-popover', KpPopoverComponent);
}

// Side-effect: importing this entry auto-registers the element, mirroring the
// all-in-one bundle (`import '@kanso-protocol/elements/popover'`).
if (typeof customElements !== 'undefined') {
  void defineKpPopover();
}
