// AUTO-GENERATED by scripts/generate-elements-registry.js — do not edit.
import { KpProgressCircularComponent } from '@kanso-protocol/ui/progress';
import { defineKansoElement } from '../runtime';

/** Register just the `<kp-progress-circular>` custom element. Idempotent. */
export function defineKpProgressCircular(): Promise<void> {
  return defineKansoElement('kp-progress-circular', KpProgressCircularComponent);
}

// Side-effect: importing this entry auto-registers the element, mirroring the
// all-in-one bundle (`import '@kanso-protocol/elements/progress-circular'`).
if (typeof customElements !== 'undefined') {
  void defineKpProgressCircular();
}
