// AUTO-GENERATED by scripts/generate-elements-registry.js — do not edit.
import { KpProgressSegmentedComponent } from '@kanso-protocol/ui/progress';
import { defineKansoElement } from '../runtime';

/** Register just the `<kp-progress-segmented>` custom element. Idempotent. */
export function defineKpProgressSegmented(): Promise<void> {
  return defineKansoElement('kp-progress-segmented', KpProgressSegmentedComponent);
}

// Side-effect: importing this entry auto-registers the element, mirroring the
// all-in-one bundle (`import '@kanso-protocol/elements/progress-segmented'`).
if (typeof customElements !== 'undefined') {
  void defineKpProgressSegmented();
}
