// AUTO-GENERATED by scripts/generate-elements-registry.js — do not edit.
import { KpProgressLinearComponent } from '@kanso-protocol/ui/progress';
import { defineKansoElement } from '../runtime';

/** Register just the `<kp-progress-linear>` custom element. Idempotent. */
export function defineKpProgressLinear(): Promise<void> {
  return defineKansoElement('kp-progress-linear', KpProgressLinearComponent);
}

// Side-effect: importing this entry auto-registers the element, mirroring the
// all-in-one bundle (`import '@kanso-protocol/elements/progress-linear'`).
if (typeof customElements !== 'undefined') {
  void defineKpProgressLinear();
}
