// AUTO-GENERATED by scripts/generate-elements-registry.js — do not edit.
import { KpRadioGroupComponent } from '@kanso-protocol/ui/radio';
import { defineKansoElement } from '../runtime';

/** Register just the `<kp-radio-group>` custom element. Idempotent. */
export function defineKpRadioGroup(): Promise<void> {
  return defineKansoElement('kp-radio-group', KpRadioGroupComponent);
}

// Side-effect: importing this entry auto-registers the element, mirroring the
// all-in-one bundle (`import '@kanso-protocol/elements/radio-group'`).
if (typeof customElements !== 'undefined') {
  void defineKpRadioGroup();
}
