// AUTO-GENERATED by scripts/generate-elements-registry.js — do not edit.
import { KpRadioComponent } from '@kanso-protocol/ui/radio';
import { defineKansoElement } from '../runtime';

/** Register just the `<kp-radio>` custom element. Idempotent. */
export function defineKpRadio(): Promise<void> {
  return defineKansoElement('kp-radio', KpRadioComponent);
}

// Side-effect: importing this entry auto-registers the element, mirroring the
// all-in-one bundle (`import '@kanso-protocol/elements/radio'`).
if (typeof customElements !== 'undefined') {
  void defineKpRadio();
}
