// AUTO-GENERATED by scripts/generate-elements-registry.js — do not edit.
import { KpRichTextEditorComponent } from '@kanso-protocol/ui/rich-text-editor';
import { defineKansoElement } from '../runtime';

/** Register just the `<kp-rich-text-editor>` custom element. Idempotent. */
export function defineKpRichTextEditor(): Promise<void> {
  return defineKansoElement('kp-rich-text-editor', KpRichTextEditorComponent);
}

// Side-effect: importing this entry auto-registers the element, mirroring the
// all-in-one bundle (`import '@kanso-protocol/elements/rich-text-editor'`).
if (typeof customElements !== 'undefined') {
  void defineKpRichTextEditor();
}
