// AUTO-GENERATED by scripts/generate-elements-registry.js — do not edit.
import { KpRowComponent } from '@kanso-protocol/ui/row';
import { defineKansoElement } from '../runtime';

/** Register just the `<kp-row>` custom element. Idempotent. */
export function defineKpRow(): Promise<void> {
  return defineKansoElement('kp-row', KpRowComponent);
}

// Side-effect: importing this entry auto-registers the element, mirroring the
// all-in-one bundle (`import '@kanso-protocol/elements/row'`).
if (typeof customElements !== 'undefined') {
  void defineKpRow();
}
