// AUTO-GENERATED by scripts/generate-elements-registry.js — do not edit.
import { KpSearchBarComponent } from '@kanso-protocol/ui/search-bar';
import { defineKansoElement } from '../runtime';

/** Register just the `<kp-search-bar>` custom element. Idempotent. */
export function defineKpSearchBar(): Promise<void> {
  return defineKansoElement('kp-search-bar', KpSearchBarComponent);
}

// Side-effect: importing this entry auto-registers the element, mirroring the
// all-in-one bundle (`import '@kanso-protocol/elements/search-bar'`).
if (typeof customElements !== 'undefined') {
  void defineKpSearchBar();
}
