// AUTO-GENERATED by scripts/generate-elements-registry.js — do not edit.
import { KpSegmentedControlComponent } from '@kanso-protocol/ui/segmented-control';
import { defineKansoElement } from '../runtime';

/** Register just the `<kp-segmented-control>` custom element. Idempotent. */
export function defineKpSegmentedControl(): Promise<void> {
  return defineKansoElement('kp-segmented-control', KpSegmentedControlComponent);
}

// Side-effect: importing this entry auto-registers the element, mirroring the
// all-in-one bundle (`import '@kanso-protocol/elements/segmented-control'`).
if (typeof customElements !== 'undefined') {
  void defineKpSegmentedControl();
}
