// AUTO-GENERATED by scripts/generate-elements-registry.js — do not edit.
import { KpSelectComponent } from '@kanso-protocol/ui/select';
import { defineKansoElement } from '../runtime';

/** Register just the `<kp-select>` custom element. Idempotent. */
export function defineKpSelect(): Promise<void> {
  return defineKansoElement('kp-select', KpSelectComponent);
}

// Side-effect: importing this entry auto-registers the element, mirroring the
// all-in-one bundle (`import '@kanso-protocol/elements/select'`).
if (typeof customElements !== 'undefined') {
  void defineKpSelect();
}
