// AUTO-GENERATED by scripts/generate-elements-registry.js — do not edit.
import { KpSettingsPanelComponent } from '@kanso-protocol/ui/settings-panel';
import { defineKansoElement } from '../runtime';

/** Register just the `<kp-settings-panel>` custom element. Idempotent. */
export function defineKpSettingsPanel(): Promise<void> {
  return defineKansoElement('kp-settings-panel', KpSettingsPanelComponent);
}

// Side-effect: importing this entry auto-registers the element, mirroring the
// all-in-one bundle (`import '@kanso-protocol/elements/settings-panel'`).
if (typeof customElements !== 'undefined') {
  void defineKpSettingsPanel();
}
