// AUTO-GENERATED by scripts/generate-elements-registry.js — do not edit.
import { KpSettingsRowComponent } from '@kanso-protocol/ui/settings-panel';
import { defineKansoElement } from '../runtime';

/** Register just the `<kp-settings-row>` custom element. Idempotent. */
export function defineKpSettingsRow(): Promise<void> {
  return defineKansoElement('kp-settings-row', KpSettingsRowComponent);
}

// Side-effect: importing this entry auto-registers the element, mirroring the
// all-in-one bundle (`import '@kanso-protocol/elements/settings-row'`).
if (typeof customElements !== 'undefined') {
  void defineKpSettingsRow();
}
