// AUTO-GENERATED by scripts/generate-elements-registry.js — do not edit.
import { KpSidebarComponent } from '@kanso-protocol/ui/sidebar';
import { defineKansoElement } from '../runtime';

/** Register just the `<kp-sidebar>` custom element. Idempotent. */
export function defineKpSidebar(): Promise<void> {
  return defineKansoElement('kp-sidebar', KpSidebarComponent);
}

// Side-effect: importing this entry auto-registers the element, mirroring the
// all-in-one bundle (`import '@kanso-protocol/elements/sidebar'`).
if (typeof customElements !== 'undefined') {
  void defineKpSidebar();
}
