// AUTO-GENERATED by scripts/generate-elements-registry.js — do not edit.
import { KpSkeletonComponent } from '@kanso-protocol/ui/skeleton';
import { defineKansoElement } from '../runtime';

/** Register just the `<kp-skeleton>` custom element. Idempotent. */
export function defineKpSkeleton(): Promise<void> {
  return defineKansoElement('kp-skeleton', KpSkeletonComponent);
}

// Side-effect: importing this entry auto-registers the element, mirroring the
// all-in-one bundle (`import '@kanso-protocol/elements/skeleton'`).
if (typeof customElements !== 'undefined') {
  void defineKpSkeleton();
}
