// AUTO-GENERATED by scripts/generate-elements-registry.js — do not edit.
import { KpSliderComponent } from '@kanso-protocol/ui/slider';
import { defineKansoElement } from '../runtime';

/** Register just the `<kp-slider>` custom element. Idempotent. */
export function defineKpSlider(): Promise<void> {
  return defineKansoElement('kp-slider', KpSliderComponent);
}

// Side-effect: importing this entry auto-registers the element, mirroring the
// all-in-one bundle (`import '@kanso-protocol/elements/slider'`).
if (typeof customElements !== 'undefined') {
  void defineKpSlider();
}
