// AUTO-GENERATED by scripts/generate-elements-registry.js — do not edit.
import { KpStackComponent } from '@kanso-protocol/ui/stack';
import { defineKansoElement } from '../runtime';

/** Register just the `<kp-stack>` custom element. Idempotent. */
export function defineKpStack(): Promise<void> {
  return defineKansoElement('kp-stack', KpStackComponent);
}

// Side-effect: importing this entry auto-registers the element, mirroring the
// all-in-one bundle (`import '@kanso-protocol/elements/stack'`).
if (typeof customElements !== 'undefined') {
  void defineKpStack();
}
