// AUTO-GENERATED by scripts/generate-elements-registry.js — do not edit.
import { KpStatCardComponent } from '@kanso-protocol/ui/stat-card';
import { defineKansoElement } from '../runtime';

/** Register just the `<kp-stat-card>` custom element. Idempotent. */
export function defineKpStatCard(): Promise<void> {
  return defineKansoElement('kp-stat-card', KpStatCardComponent);
}

// Side-effect: importing this entry auto-registers the element, mirroring the
// all-in-one bundle (`import '@kanso-protocol/elements/stat-card'`).
if (typeof customElements !== 'undefined') {
  void defineKpStatCard();
}
