// AUTO-GENERATED by scripts/generate-elements-registry.js — do not edit.
import { KpTableToolbarComponent } from '@kanso-protocol/ui/table-toolbar';
import { defineKansoElement } from '../runtime';

/** Register just the `<kp-table-toolbar>` custom element. Idempotent. */
export function defineKpTableToolbar(): Promise<void> {
  return defineKansoElement('kp-table-toolbar', KpTableToolbarComponent);
}

// Side-effect: importing this entry auto-registers the element, mirroring the
// all-in-one bundle (`import '@kanso-protocol/elements/table-toolbar'`).
if (typeof customElements !== 'undefined') {
  void defineKpTableToolbar();
}
