// AUTO-GENERATED by scripts/generate-elements-registry.js — do not edit.
import { KpTableVirtualComponent } from '@kanso-protocol/ui/table-virtual';
import { defineKansoElement } from '../runtime';

/** Register just the `<kp-table-virtual>` custom element. Idempotent. */
export function defineKpTableVirtual(): Promise<void> {
  return defineKansoElement('kp-table-virtual', KpTableVirtualComponent);
}

// Side-effect: importing this entry auto-registers the element, mirroring the
// all-in-one bundle (`import '@kanso-protocol/elements/table-virtual'`).
if (typeof customElements !== 'undefined') {
  void defineKpTableVirtual();
}
