// AUTO-GENERATED by scripts/generate-elements-registry.js — do not edit.
import { KpTableComponent } from '@kanso-protocol/ui/table';
import { defineKansoElement } from '../runtime';

/** Register just the `<kp-table>` custom element. Idempotent. */
export function defineKpTable(): Promise<void> {
  return defineKansoElement('kp-table', KpTableComponent);
}

// Side-effect: importing this entry auto-registers the element, mirroring the
// all-in-one bundle (`import '@kanso-protocol/elements/table'`).
if (typeof customElements !== 'undefined') {
  void defineKpTable();
}
