// AUTO-GENERATED by scripts/generate-elements-registry.js — do not edit.
import { KpTabsComponent } from '@kanso-protocol/ui/tabs';
import { defineKansoElement } from '../runtime';

/** Register just the `<kp-tabs>` custom element. Idempotent. */
export function defineKpTabs(): Promise<void> {
  return defineKansoElement('kp-tabs', KpTabsComponent);
}

// Side-effect: importing this entry auto-registers the element, mirroring the
// all-in-one bundle (`import '@kanso-protocol/elements/tabs'`).
if (typeof customElements !== 'undefined') {
  void defineKpTabs();
}
