// AUTO-GENERATED by scripts/generate-elements-registry.js — do not edit.
import { KpTextareaComponent } from '@kanso-protocol/ui/textarea';
import { defineKansoElement } from '../runtime';

/** Register just the `<kp-textarea>` custom element. Idempotent. */
export function defineKpTextarea(): Promise<void> {
  return defineKansoElement('kp-textarea', KpTextareaComponent);
}

// Side-effect: importing this entry auto-registers the element, mirroring the
// all-in-one bundle (`import '@kanso-protocol/elements/textarea'`).
if (typeof customElements !== 'undefined') {
  void defineKpTextarea();
}
