// AUTO-GENERATED by scripts/generate-elements-registry.js — do not edit.
import { KpThemeToggleComponent } from '@kanso-protocol/ui/theme-toggle';
import { defineKansoElement } from '../runtime';

/** Register just the `<kp-theme-toggle>` custom element. Idempotent. */
export function defineKpThemeToggle(): Promise<void> {
  return defineKansoElement('kp-theme-toggle', KpThemeToggleComponent);
}

// Side-effect: importing this entry auto-registers the element, mirroring the
// all-in-one bundle (`import '@kanso-protocol/elements/theme-toggle'`).
if (typeof customElements !== 'undefined') {
  void defineKpThemeToggle();
}
