// AUTO-GENERATED by scripts/generate-elements-registry.js — do not edit.
import { KpTimePickerComponent } from '@kanso-protocol/ui/timepicker';
import { defineKansoElement } from '../runtime';

/** Register just the `<kp-time-picker>` custom element. Idempotent. */
export function defineKpTimePicker(): Promise<void> {
  return defineKansoElement('kp-time-picker', KpTimePickerComponent);
}

// Side-effect: importing this entry auto-registers the element, mirroring the
// all-in-one bundle (`import '@kanso-protocol/elements/time-picker'`).
if (typeof customElements !== 'undefined') {
  void defineKpTimePicker();
}
