// AUTO-GENERATED by scripts/generate-elements-registry.js — do not edit.
import { KpToastHostComponent } from '@kanso-protocol/ui/toast';
import { defineKansoElement } from '../runtime';

/** Register just the `<kp-toast-host>` custom element. Idempotent. */
export function defineKpToastHost(): Promise<void> {
  return defineKansoElement('kp-toast-host', KpToastHostComponent);
}

// Side-effect: importing this entry auto-registers the element, mirroring the
// all-in-one bundle (`import '@kanso-protocol/elements/toast-host'`).
if (typeof customElements !== 'undefined') {
  void defineKpToastHost();
}
