// AUTO-GENERATED by scripts/generate-elements-registry.js — do not edit.
import { KpToggleComponent } from '@kanso-protocol/ui/toggle';
import { defineKansoElement } from '../runtime';

/** Register just the `<kp-toggle>` custom element. Idempotent. */
export function defineKpToggle(): Promise<void> {
  return defineKansoElement('kp-toggle', KpToggleComponent);
}

// Side-effect: importing this entry auto-registers the element, mirroring the
// all-in-one bundle (`import '@kanso-protocol/elements/toggle'`).
if (typeof customElements !== 'undefined') {
  void defineKpToggle();
}
