// AUTO-GENERATED by scripts/generate-elements-registry.js — do not edit.
import { KpTreeComponent } from '@kanso-protocol/ui/tree';
import { defineKansoElement } from '../runtime';

/** Register just the `<kp-tree>` custom element. Idempotent. */
export function defineKpTree(): Promise<void> {
  return defineKansoElement('kp-tree', KpTreeComponent);
}

// Side-effect: importing this entry auto-registers the element, mirroring the
// all-in-one bundle (`import '@kanso-protocol/elements/tree'`).
if (typeof customElements !== 'undefined') {
  void defineKpTree();
}
