// AUTO-GENERATED by scripts/generate-elements-registry.js — do not edit.
import { KpUserMenuComponent } from '@kanso-protocol/ui/user-menu';
import { defineKansoElement } from '../runtime';

/** Register just the `<kp-user-menu>` custom element. Idempotent. */
export function defineKpUserMenu(): Promise<void> {
  return defineKansoElement('kp-user-menu', KpUserMenuComponent);
}

// Side-effect: importing this entry auto-registers the element, mirroring the
// all-in-one bundle (`import '@kanso-protocol/elements/user-menu'`).
if (typeof customElements !== 'undefined') {
  void defineKpUserMenu();
}
