// AUTO-GENERATED by scripts/generate-elements-registry.js — do not edit.
import { KpVariableVirtualListComponent } from '@kanso-protocol/ui/variable-virtual-list';
import { defineKansoElement } from '../runtime';

/** Register just the `<kp-variable-virtual-list>` custom element. Idempotent. */
export function defineKpVariableVirtualList(): Promise<void> {
  return defineKansoElement('kp-variable-virtual-list', KpVariableVirtualListComponent);
}

// Side-effect: importing this entry auto-registers the element, mirroring the
// all-in-one bundle (`import '@kanso-protocol/elements/variable-virtual-list'`).
if (typeof customElements !== 'undefined') {
  void defineKpVariableVirtualList();
}
