// AUTO-GENERATED by scripts/generate-elements-registry.js — do not edit.
import { KpVirtualListComponent } from '@kanso-protocol/ui/virtual-list';
import { defineKansoElement } from '../runtime';

/** Register just the `<kp-virtual-list>` custom element. Idempotent. */
export function defineKpVirtualList(): Promise<void> {
  return defineKansoElement('kp-virtual-list', KpVirtualListComponent);
}

// Side-effect: importing this entry auto-registers the element, mirroring the
// all-in-one bundle (`import '@kanso-protocol/elements/virtual-list'`).
if (typeof customElements !== 'undefined') {
  void defineKpVirtualList();
}
